do
    local _ = {
        ['artillery-turret'] = {
            cannon_barrel_recoil_shiftings_load_correction_matrix = {{0, 0.25, 0}, {-0.25, 0, 0}, {0, 0, 0.25}},
            close_sound = {{filename = '__base__/sound/artillery-close.ogg', volume = 0.6}},
            cannon_barrel_light_direction = {0.5976251, 0.0242053, -0.8014102},
            alert_when_attacking = false,
            base_picture_render_layer = 'lower-object-above-shadow',
            collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
            corpse = 'artillery-turret-remnants',
            inventory_size = 1,
            dying_explosion = 'artillery-turret-explosion',
            icon_mipmaps = 4,
            cannon_barrel_pictures = {
                layers = {
                    {
                        line_length = 4,
                        priority = 'very-low',
                        width = 266,
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-16.png'
                        },
                        lines_per_file = 4,
                        hr_version = {
                            line_length = 4,
                            priority = 'very-low',
                            width = 530,
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-16.png'
                            },
                            lines_per_file = 4,
                            direction_count = 256,
                            scale = 0.5,
                            height = 384,
                            shift = {0, -1.75}
                        },
                        direction_count = 256,
                        height = 192,
                        shift = {0, -1.75}
                    }, {
                        draw_as_shadow = true,
                        priority = 'very-low',
                        width = 454,
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-16.png'
                        },
                        lines_per_file = 4,
                        hr_version = {
                            draw_as_shadow = true,
                            priority = 'very-low',
                            width = 906,
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-16.png'
                            },
                            lines_per_file = 4,
                            direction_count = 256,
                            scale = 0.5,
                            height = 626,
                            shift = {1.703125, 1.671875},
                            line_length = 4
                        },
                        direction_count = 256,
                        height = 314,
                        shift = {1.71875, 1.6875},
                        line_length = 4
                    }
                }
            },
            cannon_base_pictures = {
                layers = {
                    {
                        line_length = 4,
                        priority = 'very-low',
                        width = 180,
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-16.png'
                        },
                        lines_per_file = 4,
                        hr_version = {
                            line_length = 4,
                            priority = 'very-low',
                            width = 358,
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-16.png'
                            },
                            lines_per_file = 4,
                            direction_count = 256,
                            scale = 0.5,
                            height = 270,
                            shift = {0, -1.265625}
                        },
                        direction_count = 256,
                        height = 136,
                        shift = {0, -1.25}
                    }, {
                        draw_as_shadow = true,
                        priority = 'very-low',
                        width = 238,
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-16.png'
                        },
                        lines_per_file = 4,
                        hr_version = {
                            draw_as_shadow = true,
                            priority = 'very-low',
                            width = 476,
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-16.png'
                            },
                            lines_per_file = 4,
                            direction_count = 256,
                            scale = 0.5,
                            height = 340,
                            shift = {3.515625, 1.40625},
                            line_length = 4
                        },
                        direction_count = 256,
                        height = 170,
                        shift = {3.5, 1.40625},
                        line_length = 4
                    }
                }
            },
            turret_rotation_speed = 0.001,
            base_picture = {
                layers = {
                    {
                        filename = '__base__/graphics/entity/artillery-turret/artillery-turret-base.png',
                        width = 104,
                        direction_count = 1,
                        frame_count = 1,
                        height = 100,
                        shift = {-0, 0.6875},
                        priority = 'high',
                        hr_version = {
                            filename = '__base__/graphics/entity/artillery-turret/hr-artillery-turret-base.png',
                            line_length = 1,
                            priority = 'high',
                            frame_count = 1,
                            width = 207,
                            direction_count = 1,
                            scale = 0.5,
                            height = 199,
                            shift = {-0, 0.6875}
                        }
                    }, {
                        filename = '__base__/graphics/entity/artillery-turret/artillery-turret-base-shadow.png',
                        draw_as_shadow = true,
                        priority = 'high',
                        frame_count = 1,
                        width = 138,
                        hr_version = {
                            filename = '__base__/graphics/entity/artillery-turret/hr-artillery-turret-base-shadow.png',
                            draw_as_shadow = true,
                            priority = 'high',
                            frame_count = 1,
                            width = 277,
                            direction_count = 1,
                            scale = 0.5,
                            height = 149,
                            shift = {0.5625, 1.1875},
                            line_length = 1
                        },
                        direction_count = 1,
                        height = 75,
                        shift = {0.5625, 1.1875},
                        line_length = 1
                    }
                }
            },
            mined_sound = {filename = '__core__/sound/deconstruct-large.ogg', volume = 0.8},
            resistances = {
                {decrease = 15, percent = 50, type = 'fire'}, {decrease = 15, percent = 30, type = 'physical'},
                {decrease = 50, percent = 50, type = 'impact'}, {decrease = 15, percent = 30, type = 'explosion'},
                {decrease = 3, percent = 20, type = 'acid'}
            },
            automated_ammo_count = 5,
            rotating_sound = {sound = {filename = '__base__/sound/fight/artillery-rotation-loop.ogg', volume = 0.6}},
            cannon_barrel_recoil_shiftings = {
                {y = 0.04, x = -0, z = -0}, {y = 0.037, x = -0.789, z = -0.351}, {y = 0.035, x = -1.578, z = -0.702},
                {y = 0.033, x = -2.367, z = -1.054}, {y = 0.031, x = -3.155, z = -1.405},
                {y = 0.028, x = -3.944, z = -1.756}, {y = 0.028, x = -3.931, z = -1.75},
                {y = 0.028, x = -3.901, z = -1.737}, {y = 0.029, x = -3.854, z = -1.716},
                {y = 0.029, x = -3.79, z = -1.688}, {y = 0.029, x = -3.711, z = -1.652},
                {y = 0.029, x = -3.617, z = -1.61}, {y = 0.03, x = -3.508, z = -1.562},
                {y = 0.03, x = -3.385, z = -1.507}, {y = 0.03, x = -3.249, z = -1.447},
                {y = 0.031, x = -3.102, z = -1.381}, {y = 0.031, x = -2.944, z = -1.311},
                {y = 0.032, x = -2.776, z = -1.236}, {y = 0.032, x = -2.599, z = -1.157},
                {y = 0.033, x = -2.416, z = -1.076}, {y = 0.033, x = -2.226, z = -0.991},
                {y = 0.034, x = -2.032, z = -0.905}, {y = 0.034, x = -1.835, z = -0.817},
                {y = 0.035, x = -1.635, z = -0.728}, {y = 0.035, x = -1.436, z = -0.639},
                {y = 0.036, x = -1.238, z = -0.551}, {y = 0.037, x = -1.042, z = -0.464},
                {y = 0.037, x = -0.851, z = -0.379}, {y = 0.038, x = -0.665, z = -0.296},
                {y = 0.038, x = -0.485, z = -0.216}, {y = 0.039, x = -0.314, z = -0.14},
                {y = 0.039, x = -0.152, z = -0.068}
            },
            cannon_parking_speed = 0.25,
            vehicle_impact_sound = 0,
            name = 'artillery-turret',
            type = 'artillery-turret',
            icon = '__base__/graphics/icons/artillery-turret.png',
            gun = 'artillery-wagon-cannon',
            selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
            icon_size = 64,
            rotating_stopped_sound = {filename = '__base__/sound/fight/artillery-rotation-stop.ogg'},
            drawing_box = {{-1.5, -5}, {1.5, 1.5}},
            water_reflection = {
                rotate = false,
                pictures = {
                    filename = '__base__/graphics/entity/artillery-turret/artillery-turret-reflection.png',
                    priority = 'extra-high',
                    scale = 5,
                    height = 32,
                    variation_count = 1,
                    width = 28,
                    shift = {0, 2.34375}
                },
                orientation_to_variation = false
            },
            damaged_trigger_effect = {
                damage_type_filters = 'fire',
                entity_name = 'spark-explosion',
                type = 'create-entity',
                offsets = {{0, 1}},
                offset_deviation = {{-0.5, -0.5}, {0.5, 0.5}}
            },
            max_health = 2000,
            flags = {'placeable-neutral', 'placeable-player', 'player-creation'},
            manual_range_modifier = 2.5,
            turn_after_shooting_cooldown = 60,
            base_shift = {0, -0.6875},
            ammo_stack_limit = 15,
            open_sound = {{filename = '__base__/sound/artillery-open.ogg', volume = 0.57}},
            cannon_parking_frame_count = 8,
            minable = {mining_time = 0.5, result = 'artillery-turret'}
        }
    };
    return _;
end
