do
    local _ = {
        ['artillery-wagon'] = {
            minable = {mining_time = 0.5, result = 'artillery-wagon'},
            working_sound = {
                sound = {volume = 0.3, filename = '__base__/sound/train-wheels.ogg'},
                match_volume_to_activity = true
            },
            vehicle_impact_sound = 0,
            crash_trigger = {type = 'play-sound', sound = {{volume = 0, filename = '__base__/sound/car-crash.ogg'}}},
            ammo_stack_limit = 100,
            cannon_barrel_recoil_shiftings = {
                {y = 0.04, z = -0, x = -0}, {y = 0.037, z = -0.351, x = -0.789}, {y = 0.035, z = -0.702, x = -1.578},
                {y = 0.033, z = -1.054, x = -2.367}, {y = 0.031, z = -1.405, x = -3.155},
                {y = 0.028, z = -1.756, x = -3.944}, {y = 0.028, z = -1.75, x = -3.931},
                {y = 0.028, z = -1.737, x = -3.901}, {y = 0.029, z = -1.716, x = -3.854},
                {y = 0.029, z = -1.688, x = -3.79}, {y = 0.029, z = -1.652, x = -3.711},
                {y = 0.029, z = -1.61, x = -3.617}, {y = 0.03, z = -1.562, x = -3.508},
                {y = 0.03, z = -1.507, x = -3.385}, {y = 0.03, z = -1.447, x = -3.249},
                {y = 0.031, z = -1.381, x = -3.102}, {y = 0.031, z = -1.311, x = -2.944},
                {y = 0.032, z = -1.236, x = -2.776}, {y = 0.032, z = -1.157, x = -2.599},
                {y = 0.033, z = -1.076, x = -2.416}, {y = 0.033, z = -0.991, x = -2.226},
                {y = 0.034, z = -0.905, x = -2.032}, {y = 0.034, z = -0.817, x = -1.835},
                {y = 0.035, z = -0.728, x = -1.635}, {y = 0.035, z = -0.639, x = -1.436},
                {y = 0.036, z = -0.551, x = -1.238}, {y = 0.037, z = -0.464, x = -1.042},
                {y = 0.037, z = -0.379, x = -0.851}, {y = 0.038, z = -0.296, x = -0.665},
                {y = 0.038, z = -0.216, x = -0.485}, {y = 0.039, z = -0.14, x = -0.314},
                {y = 0.039, z = -0.068, x = -0.152}
            },
            drive_over_tie_trigger = {
                type = 'play-sound',
                sound = {
                    {volume = 0.4, filename = '__base__/sound/train-tie-1.ogg'},
                    {volume = 0.4, filename = '__base__/sound/train-tie-2.ogg'},
                    {volume = 0.4, filename = '__base__/sound/train-tie-3.ogg'},
                    {volume = 0.4, filename = '__base__/sound/train-tie-4.ogg'},
                    {volume = 0.4, filename = '__base__/sound/train-tie-5.ogg'},
                    {volume = 0.4, filename = '__base__/sound/train-tie-6.ogg'}
                }
            },
            pictures = {
                layers = {
                    {
                        direction_count = 256,
                        hr_version = {
                            direction_count = 256,
                            width = 476,
                            dice = 4,
                            allow_low_quality_rotation = true,
                            priority = 'very-low',
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-16.png'
                            },
                            height = 410,
                            scale = 0.5,
                            line_length = 4,
                            lines_per_file = 4,
                            shift = {0.015625, -0.859375}
                        },
                        width = 238,
                        dice = 4,
                        allow_low_quality_rotation = true,
                        priority = 'very-low',
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-16.png'
                        },
                        height = 206,
                        line_length = 4,
                        lines_per_file = 4,
                        shift = {0, -0.84375}
                    }, {
                        direction_count = 256,
                        hr_version = {
                            direction_count = 256,
                            width = 598,
                            dice = 4,
                            allow_low_quality_rotation = true,
                            priority = 'very-low',
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-base-shadow-16.png'
                            },
                            height = 480,
                            scale = 0.5,
                            line_length = 4,
                            draw_as_shadow = true,
                            shift = {1.140625, 0.203125},
                            lines_per_file = 4
                        },
                        width = 300,
                        dice = 4,
                        allow_low_quality_rotation = true,
                        priority = 'very-low',
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-base-shadow-16.png'
                        },
                        height = 240,
                        line_length = 4,
                        draw_as_shadow = true,
                        shift = {1.15625, 0.1875},
                        lines_per_file = 4
                    }
                }
            },
            weight = 4000,
            cannon_barrel_light_direction = {0.5976251, 0.0242053, -0.8014102},
            rotating_sound = {sound = {volume = 0.2, filename = '__base__/sound/fight/artillery-rotation-loop.ogg'}},
            collision_box = {{-0.6, -2.4}, {0.6, 2.4}},
            dying_explosion = 'artillery-wagon-explosion',
            braking_force = 3,
            stand_by_light = {
                {
                    color = {a = 0, b = 1, g = 0.2, r = 0.05},
                    size = 2,
                    shift = {-0.6, -3.5},
                    add_perspective = true,
                    intensity = 0.5,
                    minimum_darkness = 0.3
                }, {
                    color = {a = 0, b = 1, g = 0.2, r = 0.05},
                    size = 2,
                    shift = {0.6, -3.5},
                    add_perspective = true,
                    intensity = 0.5,
                    minimum_darkness = 0.3
                }
            },
            wheels = {
                direction_count = 256,
                height = 115,
                width = 115,
                priority = 'very-low',
                line_length = 8,
                lines_per_file = 16,
                hr_version = {
                    direction_count = 256,
                    height = 227,
                    scale = 0.5,
                    width = 229,
                    line_length = 4,
                    lines_per_file = 8,
                    priority = 'very-low',
                    filenames = {
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-1.png',
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-2.png',
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-3.png',
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-4.png',
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-5.png',
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-6.png',
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-7.png',
                        '__base__/graphics/entity/diesel-locomotive/hr-train-wheels-8.png'
                    }
                },
                filenames = {
                    '__base__/graphics/entity/diesel-locomotive/train-wheels-01.png',
                    '__base__/graphics/entity/diesel-locomotive/train-wheels-02.png'
                }
            },
            turret_rotation_speed = 0.001,
            icon_mipmaps = 4,
            back_light = {
                {
                    color = {a = 0, b = 0.05, g = 0.1, r = 1},
                    size = 2,
                    shift = {-0.6, 3.5},
                    add_perspective = true,
                    intensity = 0.6,
                    minimum_darkness = 0.3
                }, {
                    color = {a = 0, b = 0.05, g = 0.1, r = 1},
                    size = 2,
                    shift = {0.6, 3.5},
                    add_perspective = true,
                    intensity = 0.6,
                    minimum_darkness = 0.3
                }
            },
            vertical_selection_shift = -0.796875,
            open_sound = 0,
            type = 'artillery-wagon',
            water_reflection = {
                rotate = true,
                orientation_to_variation = false,
                pictures = {
                    filename = '__base__/graphics/entity/artillery-wagon/artillery-wagon-reflection.png',
                    scale = 5,
                    width = 32,
                    variation_count = 1,
                    priority = 'extra-high',
                    shift = {0, 1.25},
                    height = 52
                }
            },
            turn_after_shooting_cooldown = 60,
            cannon_base_pictures = {
                layers = {
                    {
                        direction_count = 256,
                        hr_version = {
                            direction_count = 256,
                            width = 358,
                            priority = 'very-low',
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-16.png'
                            },
                            height = 270,
                            scale = 0.5,
                            line_length = 4,
                            lines_per_file = 4,
                            shift = {0, -1.265625}
                        },
                        width = 180,
                        priority = 'very-low',
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-16.png'
                        },
                        height = 136,
                        line_length = 4,
                        lines_per_file = 4,
                        shift = {0, -1.25}
                    }, {
                        direction_count = 256,
                        hr_version = {
                            direction_count = 256,
                            width = 476,
                            priority = 'very-low',
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-base-shadow-16.png'
                            },
                            height = 340,
                            scale = 0.5,
                            line_length = 4,
                            draw_as_shadow = true,
                            shift = {3.515625, 1.40625},
                            lines_per_file = 4
                        },
                        width = 238,
                        priority = 'very-low',
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-base-shadow-16.png'
                        },
                        height = 170,
                        line_length = 4,
                        draw_as_shadow = true,
                        shift = {3.5, 1.40625},
                        lines_per_file = 4
                    }
                }
            },
            cannon_barrel_pictures = {
                layers = {
                    {
                        direction_count = 256,
                        hr_version = {
                            direction_count = 256,
                            width = 530,
                            priority = 'very-low',
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-16.png'
                            },
                            height = 384,
                            scale = 0.5,
                            line_length = 4,
                            lines_per_file = 4,
                            shift = {0, -1.75}
                        },
                        width = 266,
                        priority = 'very-low',
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-16.png'
                        },
                        height = 192,
                        line_length = 4,
                        lines_per_file = 4,
                        shift = {0, -1.75}
                    }, {
                        direction_count = 256,
                        hr_version = {
                            direction_count = 256,
                            width = 906,
                            priority = 'very-low',
                            filenames = {
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-1.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-2.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-3.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-4.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-5.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-6.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-7.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-8.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-9.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-10.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-11.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-12.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-13.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-14.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-15.png',
                                '__base__/graphics/entity/artillery-wagon/hr-artillery-wagon-cannon-barrel-shadow-16.png'
                            },
                            height = 626,
                            scale = 0.5,
                            line_length = 4,
                            draw_as_shadow = true,
                            shift = {1.703125, 1.671875},
                            lines_per_file = 4
                        },
                        width = 454,
                        priority = 'very-low',
                        filenames = {
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-1.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-2.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-3.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-4.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-5.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-6.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-7.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-8.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-9.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-10.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-11.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-12.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-13.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-14.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-15.png',
                            '__base__/graphics/entity/artillery-wagon/artillery-wagon-cannon-barrel-shadow-16.png'
                        },
                        height = 314,
                        line_length = 4,
                        draw_as_shadow = true,
                        shift = {1.71875, 1.6875},
                        lines_per_file = 4
                    }
                }
            },
            sound_minimum_speed = 0.1,
            selection_box = {{-1, -2.703125}, {1, 3.296875}},
            cannon_barrel_recoil_shiftings_load_correction_matrix = {{0, 0.25, 0}, {-0.25, 0, 0}, {0, 0, 0.25}},
            selected_minimap_representation = {
                flags = {'icon'},
                filename = '__base__/graphics/entity/artillery-wagon/artillery-wagon-selected-minimap-representation.png',
                scale = 0.5,
                size = {20, 40}
            },
            close_sound = 0,
            friction_force = 0.5,
            manual_range_modifier = 2.5,
            minimap_representation = {
                flags = {'icon'},
                filename = '__base__/graphics/entity/artillery-wagon/artillery-wagon-minimap-representation.png',
                scale = 0.5,
                size = {20, 40}
            },
            corpse = 'artillery-wagon-remnants',
            energy_per_hit_point = 2,
            cannon_parking_frame_count = 8,
            tie_distance = 50,
            max_speed = 1.5,
            air_resistance = 0.015,
            mined_sound = {volume = 0.8, filename = '__core__/sound/deconstruct-large.ogg'},
            max_health = 600,
            icon_size = 64,
            rotating_stopped_sound = {filename = '__base__/sound/fight/artillery-rotation-stop.ogg'},
            damaged_trigger_effect = {
                damage_type_filters = 'fire',
                offsets = {{0, 1}},
                type = 'create-entity',
                offset_deviation = {{-0.5, -0.5}, {0.5, 0.5}},
                entity_name = 'spark-explosion'
            },
            resistances = {
                {percent = 50, type = 'fire', decrease = 15}, {percent = 30, type = 'physical', decrease = 15},
                {percent = 50, type = 'impact', decrease = 50}, {percent = 30, type = 'explosion', decrease = 15},
                {percent = 20, type = 'acid', decrease = 3}
            },
            icon = '__base__/graphics/icons/artillery-wagon.png',
            connection_distance = 3,
            color = {a = 0.5, b = 0, g = 0.23, r = 0.43},
            flags = {'placeable-neutral', 'player-creation', 'placeable-off-grid'},
            gun = 'artillery-wagon-cannon',
            joint_distance = 4,
            inventory_size = 1,
            cannon_parking_speed = 0.25,
            name = 'artillery-wagon',
            cannon_base_shiftings = {
                {0, 0.609375}, {-0.046875, 0.59375}, {-0.109375, 0.59375}, {-0.171875, 0.578125}, {-0.234375, 0.578125},
                {-0.28125, 0.5625}, {-0.34375, 0.546875}, {-0.40625, 0.546875}, {-0.46875, 0.53125},
                {-0.515625, 0.515625}, {-0.578125, 0.5}, {-0.640625, 0.484375}, {-0.6875, 0.46875}, {-0.75, 0.453125},
                {-0.796875, 0.4375}, {-0.859375, 0.40625}, {-0.90625, 0.390625}, {-0.953125, 0.375}, {-1, 0.34375},
                {-1.0625, 0.328125}, {-1.109375, 0.296875}, {-1.15625, 0.28125}, {-1.203125, 0.25}, {-1.25, 0.234375},
                {-1.296875, 0.203125}, {-1.328125, 0.171875}, {-1.375, 0.140625}, {-1.421875, 0.125},
                {-1.453125, 0.09375}, {-1.5, 0.0625}, {-1.53125, 0.03125}, {-1.578125, 0}, {-1.609375, -0.015625},
                {-1.640625, -0.046875}, {-1.671875, -0.078125}, {-1.703125, -0.109375}, {-1.734375, -0.15625},
                {-1.765625, -0.1875}, {-1.796875, -0.21875}, {-1.8125, -0.25}, {-1.84375, -0.28125},
                {-1.875, -0.328125}, {-1.890625, -0.359375}, {-1.90625, -0.390625}, {-1.9375, -0.421875},
                {-1.953125, -0.46875}, {-1.96875, -0.5}, {-1.984375, -0.53125}, {-2, -0.578125}, {-2.015625, -0.609375},
                {-2.03125, -0.65625}, {-2.03125, -0.6875}, {-2.046875, -0.71875}, {-2.046875, -0.765625},
                {-2.0625, -0.796875}, {-2.0625, -0.828125}, {-2.0625, -0.875}, {-2.078125, -0.90625},
                {-2.078125, -0.9375}, {-2.078125, -0.984375}, {-2.078125, -1.015625}, {-2.0625, -1.0625},
                {-2.0625, -1.09375}, {-2.0625, -1.125}, {-2.046875, -1.15625}, {-2.0625, -1.203125},
                {-2.0625, -1.234375}, {-2.078125, -1.265625}, {-2.078125, -1.3125}, {-2.078125, -1.34375},
                {-2.078125, -1.375}, {-2.078125, -1.421875}, {-2.078125, -1.453125}, {-2.078125, -1.5},
                {-2.0625, -1.53125}, {-2.0625, -1.5625}, {-2.046875, -1.609375}, {-2.046875, -1.640625},
                {-2.03125, -1.671875}, {-2.015625, -1.71875}, {-2.015625, -1.75}, {-2, -1.796875},
                {-1.984375, -1.828125}, {-1.96875, -1.859375}, {-1.953125, -1.90625}, {-1.921875, -1.9375},
                {-1.90625, -1.96875}, {-1.890625, -2}, {-1.859375, -2.046875}, {-1.84375, -2.078125},
                {-1.8125, -2.109375}, {-1.78125, -2.140625}, {-1.75, -2.1875}, {-1.71875, -2.21875}, {-1.6875, -2.25},
                {-1.65625, -2.28125}, {-1.625, -2.3125}, {-1.59375, -2.34375}, {-1.5625, -2.375}, {-1.515625, -2.40625},
                {-1.484375, -2.4375}, {-1.4375, -2.46875}, {-1.40625, -2.5}, {-1.359375, -2.53125},
                {-1.3125, -2.546875}, {-1.265625, -2.578125}, {-1.234375, -2.609375}, {-1.1875, -2.625},
                {-1.140625, -2.65625}, {-1.078125, -2.671875}, {-1.03125, -2.703125}, {-0.984375, -2.71875},
                {-0.9375, -2.75}, {-0.890625, -2.765625}, {-0.828125, -2.78125}, {-0.78125, -2.8125},
                {-0.71875, -2.828125}, {-0.671875, -2.84375}, {-0.609375, -2.859375}, {-0.546875, -2.875},
                {-0.5, -2.890625}, {-0.4375, -2.90625}, {-0.375, -2.90625}, {-0.328125, -2.921875},
                {-0.265625, -2.9375}, {-0.203125, -2.9375}, {-0.140625, -2.953125}, {-0.078125, -2.953125},
                {-0.015625, -2.96875}, {0.03125, -2.96875}, {0.09375, -2.953125}, {0.15625, -2.953125},
                {0.21875, -2.9375}, {0.265625, -2.9375}, {0.328125, -2.921875}, {0.390625, -2.90625},
                {0.453125, -2.890625}, {0.515625, -2.890625}, {0.5625, -2.875}, {0.625, -2.859375},
                {0.671875, -2.84375}, {0.734375, -2.828125}, {0.78125, -2.796875}, {0.84375, -2.78125},
                {0.890625, -2.765625}, {0.953125, -2.75}, {1, -2.71875}, {1.046875, -2.703125}, {1.09375, -2.671875},
                {1.140625, -2.65625}, {1.1875, -2.625}, {1.234375, -2.609375}, {1.28125, -2.578125},
                {1.328125, -2.546875}, {1.375, -2.515625}, {1.40625, -2.5}, {1.453125, -2.46875}, {1.484375, -2.4375},
                {1.53125, -2.40625}, {1.5625, -2.375}, {1.609375, -2.34375}, {1.640625, -2.3125}, {1.671875, -2.28125},
                {1.703125, -2.25}, {1.734375, -2.21875}, {1.765625, -2.1875}, {1.796875, -2.140625},
                {1.828125, -2.109375}, {1.84375, -2.078125}, {1.875, -2.046875}, {1.890625, -2}, {1.921875, -1.96875},
                {1.9375, -1.9375}, {1.953125, -1.90625}, {1.96875, -1.859375}, {1.984375, -1.828125}, {2, -1.796875},
                {2.015625, -1.75}, {2.03125, -1.71875}, {2.046875, -1.671875}, {2.046875, -1.640625},
                {2.0625, -1.609375}, {2.078125, -1.5625}, {2.078125, -1.53125}, {2.078125, -1.5}, {2.078125, -1.453125},
                {2.09375, -1.421875}, {2.09375, -1.375}, {2.09375, -1.34375}, {2.078125, -1.3125},
                {2.078125, -1.265625}, {2.078125, -1.234375}, {2.078125, -1.203125}, {2.078125, -1.171875},
                {2.078125, -1.125}, {2.09375, -1.09375}, {2.09375, -1.0625}, {2.09375, -1.015625}, {2.09375, -0.984375},
                {2.09375, -0.953125}, {2.09375, -0.90625}, {2.09375, -0.875}, {2.09375, -0.828125},
                {2.078125, -0.796875}, {2.078125, -0.765625}, {2.0625, -0.71875}, {2.0625, -0.6875},
                {2.046875, -0.640625}, {2.03125, -0.609375}, {2.03125, -0.578125}, {2.015625, -0.53125}, {2, -0.5},
                {1.96875, -0.46875}, {1.953125, -0.421875}, {1.9375, -0.390625}, {1.921875, -0.359375},
                {1.890625, -0.3125}, {1.875, -0.28125}, {1.84375, -0.25}, {1.8125, -0.21875}, {1.796875, -0.1875},
                {1.765625, -0.140625}, {1.734375, -0.109375}, {1.703125, -0.078125}, {1.671875, -0.046875},
                {1.625, -0.015625}, {1.59375, 0}, {1.5625, 0.03125}, {1.515625, 0.0625}, {1.484375, 0.09375},
                {1.4375, 0.125}, {1.40625, 0.15625}, {1.359375, 0.171875}, {1.3125, 0.203125}, {1.265625, 0.234375},
                {1.21875, 0.25}, {1.171875, 0.28125}, {1.125, 0.3125}, {1.078125, 0.328125}, {1.03125, 0.359375},
                {0.984375, 0.375}, {0.921875, 0.390625}, {0.875, 0.421875}, {0.828125, 0.4375}, {0.765625, 0.453125},
                {0.71875, 0.46875}, {0.65625, 0.484375}, {0.59375, 0.5}, {0.546875, 0.515625}, {0.484375, 0.53125},
                {0.421875, 0.546875}, {0.359375, 0.5625}, {0.3125, 0.5625}, {0.25, 0.578125}, {0.1875, 0.59375},
                {0.125, 0.59375}
            }
        }
    };
    return _;
end
