do
    local _ = {
        ['processing-unit'] = {
            type = 'item',
            icon = '__base__/graphics/icons/processing-unit.png',
            icon_mipmaps = 4,
            order = 'g[processing-unit]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 100,
            name = 'processing-unit'
        },
        ['iron-chest'] = {
            name = 'iron-chest',
            subgroup = 'storage',
            order = 'a[items]-b[iron-chest]',
            icon_size = 64,
            place_result = 'iron-chest',
            icon = '__base__/graphics/icons/iron-chest.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['electronic-circuit'] = {
            type = 'item',
            icon = '__base__/graphics/icons/electronic-circuit.png',
            icon_mipmaps = 4,
            order = 'e[electronic-circuit]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 200,
            name = 'electronic-circuit'
        },
        ['fast-underground-belt'] = {
            name = 'fast-underground-belt',
            subgroup = 'belt',
            order = 'b[underground-belt]-b[fast-underground-belt]',
            icon_size = 64,
            place_result = 'fast-underground-belt',
            icon = '__base__/graphics/icons/fast-underground-belt.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['medium-electric-pole'] = {
            name = 'medium-electric-pole',
            subgroup = 'energy-pipe-distribution',
            order = 'a[energy]-b[medium-electric-pole]',
            icon_size = 64,
            place_result = 'medium-electric-pole',
            icon = '__base__/graphics/icons/medium-electric-pole.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['pipe-to-ground'] = {
            name = 'pipe-to-ground',
            subgroup = 'energy-pipe-distribution',
            order = 'a[pipe]-b[pipe-to-ground]',
            icon_size = 64,
            place_result = 'pipe-to-ground',
            icon = '__base__/graphics/icons/pipe-to-ground.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['empty-barrel'] = {
            type = 'item',
            icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png',
            icon_mipmaps = 4,
            order = 'd[empty-barrel]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 10,
            name = 'empty-barrel'
        },
        ['energy-shield-equipment'] = {
            name = 'energy-shield-equipment',
            subgroup = 'military-equipment',
            order = 'a[shield]-a[energy-shield-equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/energy-shield-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 5,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'energy-shield-equipment'
        },
        ['simple-entity-with-owner'] = {
            name = 'simple-entity-with-owner',
            subgroup = 'other',
            order = 's[simple-entity-with-owner]-o[simple-entity-with-owner]',
            icon_size = 64,
            place_result = 'simple-entity-with-owner',
            icon = '__base__/graphics/icons/wooden-chest.png',
            icon_mipmaps = 4,
            stack_size = 50,
            flags = {'hidden'},
            type = 'item'
        },
        ['rocket-fuel'] = {
            fuel_top_speed_multiplier = 1.15,
            subgroup = 'intermediate-product',
            order = 'p[rocket-fuel]',
            icon_size = 64,
            type = 'item',
            fuel_value = '100MJ',
            icon_mipmaps = 4,
            stack_size = 10,
            fuel_acceleration_multiplier = 1.8,
            name = 'rocket-fuel',
            icon = '__base__/graphics/icons/rocket-fuel.png',
            fuel_category = 'chemical'
        },
        ['assembling-machine-3'] = {
            name = 'assembling-machine-3',
            subgroup = 'production-machine',
            order = 'c[assembling-machine-3]',
            icon_size = 64,
            place_result = 'assembling-machine-3',
            icon = '__base__/graphics/icons/assembling-machine-3.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['iron-ore'] = {
            name = 'iron-ore',
            subgroup = 'raw-resource',
            order = 'e[iron-ore]',
            icon_size = 64,
            icon = '__base__/graphics/icons/iron-ore.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item',
            pictures = {
                {filename = '__base__/graphics/icons/iron-ore.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/iron-ore-1.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/iron-ore-2.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/iron-ore-3.png', size = 64, scale = 0.25, mipmap_count = 4}
            }
        },
        ['battery-mk2-equipment'] = {
            name = 'battery-mk2-equipment',
            localised_description = {'item-description.battery-equipment'},
            order = 'b[battery]-b[battery-equipment-mk2]',
            icon_size = 64,
            icon = '__base__/graphics/icons/battery-mk2-equipment.png',
            icon_mipmaps = 4,
            type = 'item',
            default_request_amount = 5,
            subgroup = 'equipment',
            stack_size = 20,
            placed_as_equipment_result = 'battery-mk2-equipment'
        },
        ['decider-combinator'] = {
            name = 'decider-combinator',
            subgroup = 'circuit-network',
            order = 'c[combinators]-b[decider-combinator]',
            icon_size = 64,
            place_result = 'decider-combinator',
            icon = '__base__/graphics/icons/decider-combinator.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['arithmetic-combinator'] = {
            name = 'arithmetic-combinator',
            subgroup = 'circuit-network',
            order = 'c[combinators]-a[arithmetic-combinator]',
            icon_size = 64,
            place_result = 'arithmetic-combinator',
            icon = '__base__/graphics/icons/arithmetic-combinator.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['fast-transport-belt'] = {
            name = 'fast-transport-belt',
            subgroup = 'belt',
            order = 'a[transport-belt]-b[fast-transport-belt]',
            icon_size = 64,
            place_result = 'fast-transport-belt',
            icon = '__base__/graphics/icons/fast-transport-belt.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['logistic-chest-storage'] = {
            name = 'logistic-chest-storage',
            subgroup = 'logistic-network',
            order = 'b[storage]-c[logistic-chest-storage]',
            icon_size = 64,
            place_result = 'logistic-chest-storage',
            icon = '__base__/graphics/icons/logistic-chest-storage.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['land-mine'] = {
            name = 'land-mine',
            subgroup = 'gun',
            order = 'f[land-mine]',
            icon_size = 64,
            place_result = 'land-mine',
            icon = '__base__/graphics/icons/land-mine.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['heat-exchanger'] = {
            name = 'heat-exchanger',
            subgroup = 'energy',
            order = 'f[nuclear-energy]-c[heat-exchanger]',
            icon_size = 64,
            place_result = 'heat-exchanger',
            icon = '__base__/graphics/icons/heat-boiler.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['logistic-chest-active-provider'] = {
            name = 'logistic-chest-active-provider',
            subgroup = 'logistic-network',
            order = 'b[storage]-c[logistic-chest-active-provider]',
            icon_size = 64,
            place_result = 'logistic-chest-active-provider',
            icon = '__base__/graphics/icons/logistic-chest-active-provider.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['red-wire'] = {
            name = 'red-wire',
            subgroup = 'circuit-network',
            order = 'b[wires]-a[red-wire]',
            icon_size = 64,
            wire_count = 1,
            icon = '__base__/graphics/icons/red-wire.png',
            icon_mipmaps = 4,
            stack_size = 200,
            type = 'item'
        },
        ['rocket-part'] = {
            name = 'rocket-part',
            subgroup = 'intermediate-product',
            order = 'q[rocket-part]',
            icon_size = 64,
            icon = '__base__/graphics/icons/rocket-part.png',
            icon_mipmaps = 4,
            stack_size = 5,
            flags = {'hidden'},
            type = 'item'
        },
        ['programmable-speaker'] = {
            name = 'programmable-speaker',
            subgroup = 'circuit-network',
            order = 'd[other]-b[programmable-speaker]',
            icon_size = 64,
            place_result = 'programmable-speaker',
            icon = '__base__/graphics/icons/programmable-speaker.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['electric-energy-interface'] = {
            name = 'electric-energy-interface',
            subgroup = 'other',
            order = 'a[electric-energy-interface]-b[electric-energy-interface]',
            icon_size = 64,
            place_result = 'electric-energy-interface',
            icon_mipmaps = 4,
            stack_size = 50,
            icons = {{tint = {g = 0.8, r = 1, a = 1, b = 1}, icon = '__base__/graphics/icons/accumulator.png'}},
            flags = {'hidden'},
            type = 'item'
        },
        ['green-wire'] = {
            name = 'green-wire',
            subgroup = 'circuit-network',
            order = 'b[wires]-b[green-wire]',
            icon_size = 64,
            wire_count = 1,
            icon = '__base__/graphics/icons/green-wire.png',
            icon_mipmaps = 4,
            stack_size = 200,
            type = 'item'
        },
        ['filter-inserter'] = {
            name = 'filter-inserter',
            subgroup = 'inserter',
            order = 'e[filter-inserter]',
            icon_size = 64,
            place_result = 'filter-inserter',
            icon = '__base__/graphics/icons/filter-inserter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['battery-equipment'] = {
            name = 'battery-equipment',
            subgroup = 'equipment',
            order = 'b[battery]-a[battery-equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/battery-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 5,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'battery-equipment'
        },
        ['crude-oil-barrel'] = {
            name = 'crude-oil-barrel',
            subgroup = 'fill-barrel',
            order = 'b[crude-oil-barrel]',
            icon_size = 64,
            localised_name = {'item-name.filled-barrel', {'fluid-name.crude-oil'}},
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {
                {icon_size = 64, icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png', icon_mipmaps = 4},
                {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-side-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0, r = 0, a = 0.75, b = 0}
                }, {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-hoop-top-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.5, r = 0.5, a = 0.75, b = 0.5}
                }
            },
            type = 'item'
        },
        ['iron-plate'] = {
            type = 'item',
            icon = '__base__/graphics/icons/iron-plate.png',
            icon_mipmaps = 4,
            order = 'b[iron-plate]',
            icon_size = 64,
            subgroup = 'raw-material',
            stack_size = 100,
            name = 'iron-plate'
        },
        ['stack-inserter'] = {
            name = 'stack-inserter',
            subgroup = 'inserter',
            order = 'f[stack-inserter]',
            icon_size = 64,
            place_result = 'stack-inserter',
            icon = '__base__/graphics/icons/stack-inserter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        computer = {
            name = 'computer',
            subgroup = 'defensive-structure',
            order = 'g[computer]',
            icon_size = 64,
            icon = '__base__/graphics/icons/computer.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['burner-mining-drill'] = {
            name = 'burner-mining-drill',
            subgroup = 'extraction-machine',
            order = 'a[items]-a[burner-mining-drill]',
            icon_size = 64,
            place_result = 'burner-mining-drill',
            icon = '__base__/graphics/icons/burner-mining-drill.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['iron-stick'] = {
            type = 'item',
            icon = '__base__/graphics/icons/iron-stick.png',
            icon_mipmaps = 4,
            order = 'b[iron-stick]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 100,
            name = 'iron-stick'
        },
        ['electric-engine-unit'] = {
            type = 'item',
            icon = '__base__/graphics/icons/electric-engine-unit.png',
            icon_mipmaps = 4,
            order = 'i[electric-engine-unit]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 50,
            name = 'electric-engine-unit'
        },
        coin = {
            name = 'coin',
            subgroup = 'science-pack',
            order = 'y',
            icon_size = 64,
            icon = '__base__/graphics/icons/coin.png',
            icon_mipmaps = 4,
            stack_size = 100000,
            flags = {'hidden'},
            type = 'item'
        },
        centrifuge = {
            name = 'centrifuge',
            subgroup = 'production-machine',
            order = 'g[centrifuge]',
            icon_size = 64,
            place_result = 'centrifuge',
            icon = '__base__/graphics/icons/centrifuge.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['used-up-uranium-fuel-cell'] = {
            type = 'item',
            icon = '__base__/graphics/icons/used-up-uranium-fuel-cell.png',
            icon_mipmaps = 4,
            order = 'r[used-up-uranium-fuel-cell]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 50,
            name = 'used-up-uranium-fuel-cell'
        },
        ['electric-mining-drill'] = {
            name = 'electric-mining-drill',
            subgroup = 'extraction-machine',
            order = 'a[items]-b[electric-mining-drill]',
            icon_size = 64,
            place_result = 'electric-mining-drill',
            icon = '__base__/graphics/icons/electric-mining-drill.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        landfill = {
            name = 'landfill',
            subgroup = 'terrain',
            order = 'c[landfill]-a[dirt]',
            icon_size = 64,
            place_as_tile = {condition = {'ground-tile'}, condition_size = 1, result = 'landfill'},
            icon = '__base__/graphics/icons/landfill.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['crash-site-chest-2'] = {
            name = 'crash-site-chest-2',
            subgroup = 'crash-site',
            order = 'x[crash-site-chest]',
            icon_size = 64,
            place_result = 'crash-site-chest-2',
            icon = '__base__/graphics/icons/crash-site-chest.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['construction-robot'] = {
            name = 'construction-robot',
            subgroup = 'logistic-network',
            order = 'a[robot]-b[construction-robot]',
            icon_size = 64,
            place_result = 'construction-robot',
            icon = '__base__/graphics/icons/construction-robot.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['laser-turret'] = {
            name = 'laser-turret',
            subgroup = 'defensive-structure',
            order = 'b[turret]-b[laser-turret]',
            icon_size = 64,
            place_result = 'laser-turret',
            icon = '__base__/graphics/icons/laser-turret.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['train-stop'] = {
            name = 'train-stop',
            subgroup = 'train-transport',
            order = 'a[train-system]-c[train-stop]',
            icon_size = 64,
            place_result = 'train-stop',
            icon = '__base__/graphics/icons/train-stop.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        splitter = {
            name = 'splitter',
            subgroup = 'belt',
            order = 'c[splitter]-a[splitter]',
            icon_size = 64,
            place_result = 'splitter',
            icon = '__base__/graphics/icons/splitter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['solar-panel-equipment'] = {
            name = 'solar-panel-equipment',
            subgroup = 'equipment',
            order = 'a[energy-source]-a[solar-panel]',
            icon_size = 64,
            icon = '__base__/graphics/icons/solar-panel-equipment.png',
            icon_mipmaps = 4,
            stack_size = 20,
            type = 'item',
            placed_as_equipment_result = 'solar-panel-equipment'
        },
        accumulator = {
            name = 'accumulator',
            subgroup = 'energy',
            order = 'e[accumulator]-a[accumulator]',
            icon_size = 64,
            place_result = 'accumulator',
            icon = '__base__/graphics/icons/accumulator.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['personal-laser-defense-equipment'] = {
            name = 'personal-laser-defense-equipment',
            subgroup = 'military-equipment',
            order = 'b[active-defense]-a[personal-laser-defense-equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/personal-laser-defense-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 5,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'personal-laser-defense-equipment'
        },
        ['crash-site-assembling-machine-1-broken'] = {
            name = 'crash-site-assembling-machine-1-broken',
            subgroup = 'crash-site',
            order = 'x[crash-site-assembling-machine-1-broken]',
            icon_size = 64,
            place_result = 'crash-site-assembling-machine-1-broken',
            icon = '__base__/graphics/icons/crash-site-assembling-machine-1-broken.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['simple-entity-with-force'] = {
            name = 'simple-entity-with-force',
            subgroup = 'other',
            order = 's[simple-entity-with-force]-f[simple-entity-with-force]',
            icon_size = 64,
            place_result = 'simple-entity-with-force',
            icon = '__base__/graphics/icons/steel-chest.png',
            icon_mipmaps = 4,
            stack_size = 50,
            flags = {'hidden'},
            type = 'item'
        },
        ['solar-panel'] = {
            name = 'solar-panel',
            subgroup = 'energy',
            order = 'd[solar-panel]-a[solar-panel]',
            icon_size = 64,
            place_result = 'solar-panel',
            icon = '__base__/graphics/icons/solar-panel.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['engine-unit'] = {
            type = 'item',
            icon = '__base__/graphics/icons/engine-unit.png',
            icon_mipmaps = 4,
            order = 'h[engine-unit]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 50,
            name = 'engine-unit'
        },
        inserter = {
            name = 'inserter',
            subgroup = 'inserter',
            order = 'b[inserter]',
            icon_size = 64,
            place_result = 'inserter',
            icon = '__base__/graphics/icons/inserter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['heavy-oil-barrel'] = {
            name = 'heavy-oil-barrel',
            subgroup = 'fill-barrel',
            order = 'b[heavy-oil-barrel]',
            icon_size = 64,
            localised_name = {'item-name.filled-barrel', {'fluid-name.heavy-oil'}},
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {
                {icon_size = 64, icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png', icon_mipmaps = 4},
                {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-side-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.04, r = 0.5, a = 0.75, b = 0}
                }, {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-hoop-top-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.6, r = 0.85, a = 0.75, b = 0.3}
                }
            },
            type = 'item'
        },
        ['night-vision-equipment'] = {
            name = 'night-vision-equipment',
            subgroup = 'equipment',
            order = 'f[night-vision]-a[night-vision-equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/night-vision-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 1,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'night-vision-equipment'
        },
        ['small-plane'] = {
            name = 'small-plane',
            subgroup = 'transport',
            order = 'b[personal-transport]-x[small-plane]',
            icon_size = 64,
            icon = '__base__/graphics/icons/small-plane.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['fast-splitter'] = {
            name = 'fast-splitter',
            subgroup = 'belt',
            order = 'c[splitter]-b[fast-splitter]',
            icon_size = 64,
            place_result = 'fast-splitter',
            icon = '__base__/graphics/icons/fast-splitter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['stack-filter-inserter'] = {
            name = 'stack-filter-inserter',
            subgroup = 'inserter',
            order = 'g[stack-filter-inserter]',
            icon_size = 64,
            place_result = 'stack-filter-inserter',
            icon = '__base__/graphics/icons/stack-filter-inserter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['petroleum-gas-barrel'] = {
            name = 'petroleum-gas-barrel',
            subgroup = 'fill-barrel',
            order = 'b[petroleum-gas-barrel]',
            icon_size = 64,
            localised_name = {'item-name.filled-barrel', {'fluid-name.petroleum-gas'}},
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {
                {icon_size = 64, icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png', icon_mipmaps = 4},
                {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-side-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.1, r = 0.3, a = 0.75, b = 0.3}
                }, {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-hoop-top-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.8, r = 0.8, a = 0.75, b = 0.8}
                }
            },
            type = 'item'
        },
        ['crash-site-assembling-machine-1-repaired'] = {
            name = 'crash-site-assembling-machine-1-repaired',
            subgroup = 'crash-site',
            order = 'x[crash-site-assembling-machine-1-repaired]',
            icon_size = 64,
            place_result = 'crash-site-assembling-machine-1-repaired',
            icon = '__base__/graphics/icons/crash-site-assembling-machine-1-repaired.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        boiler = {
            name = 'boiler',
            subgroup = 'energy',
            order = 'b[steam-power]-a[boiler]',
            icon_size = 64,
            place_result = 'boiler',
            icon = '__base__/graphics/icons/boiler.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['sulfuric-acid-barrel'] = {
            name = 'sulfuric-acid-barrel',
            subgroup = 'fill-barrel',
            order = 'b[sulfuric-acid-barrel]',
            icon_size = 64,
            localised_name = {'item-name.filled-barrel', {'fluid-name.sulfuric-acid'}},
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {
                {icon_size = 64, icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png', icon_mipmaps = 4},
                {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-side-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.65, r = 0.75, a = 0.75, b = 0.1}
                }, {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-hoop-top-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 1, r = 0.7, a = 0.75, b = 0.1}
                }
            },
            type = 'item'
        },
        ['light-oil-barrel'] = {
            name = 'light-oil-barrel',
            subgroup = 'fill-barrel',
            order = 'b[light-oil-barrel]',
            icon_size = 64,
            localised_name = {'item-name.filled-barrel', {'fluid-name.light-oil'}},
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {
                {icon_size = 64, icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png', icon_mipmaps = 4},
                {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-side-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.33, r = 0.57, a = 0.75, b = 0}
                }, {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-hoop-top-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.73, r = 1, a = 0.75, b = 0.07}
                }
            },
            type = 'item'
        },
        ['nuclear-reactor'] = {
            name = 'nuclear-reactor',
            subgroup = 'energy',
            order = 'f[nuclear-energy]-a[reactor]',
            icon_size = 64,
            place_result = 'nuclear-reactor',
            icon = '__base__/graphics/icons/nuclear-reactor.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        concrete = {
            name = 'concrete',
            subgroup = 'terrain',
            order = 'b[concrete]-a[plain]',
            icon_size = 64,
            place_as_tile = {condition = {'water-tile'}, condition_size = 1, result = 'concrete'},
            icon = '__base__/graphics/icons/concrete.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['belt-immunity-equipment'] = {
            name = 'belt-immunity-equipment',
            subgroup = 'equipment',
            order = 'c[belt-immunity]-a[belt-immunity]',
            icon_size = 64,
            icon = '__base__/graphics/icons/belt-immunity-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 1,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'belt-immunity-equipment'
        },
        ['express-transport-belt'] = {
            name = 'express-transport-belt',
            subgroup = 'belt',
            order = 'a[transport-belt]-c[express-transport-belt]',
            icon_size = 64,
            place_result = 'express-transport-belt',
            icon = '__base__/graphics/icons/express-transport-belt.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['power-switch'] = {
            name = 'power-switch',
            subgroup = 'circuit-network',
            order = 'd[other]-a[power-switch]',
            icon_size = 64,
            place_result = 'power-switch',
            icon = '__base__/graphics/icons/power-switch.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['gun-turret'] = {
            name = 'gun-turret',
            subgroup = 'defensive-structure',
            order = 'b[turret]-a[gun-turret]',
            icon_size = 64,
            place_result = 'gun-turret',
            icon = '__base__/graphics/icons/gun-turret.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['assembling-machine-2'] = {
            name = 'assembling-machine-2',
            subgroup = 'production-machine',
            order = 'b[assembling-machine-2]',
            icon_size = 64,
            place_result = 'assembling-machine-2',
            icon = '__base__/graphics/icons/assembling-machine-2.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['big-electric-pole'] = {
            name = 'big-electric-pole',
            subgroup = 'energy-pipe-distribution',
            order = 'a[energy]-c[big-electric-pole]',
            icon_size = 64,
            place_result = 'big-electric-pole',
            icon = '__base__/graphics/icons/big-electric-pole.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['logistic-chest-requester'] = {
            name = 'logistic-chest-requester',
            subgroup = 'logistic-network',
            order = 'b[storage]-e[logistic-chest-requester]',
            icon_size = 64,
            place_result = 'logistic-chest-requester',
            icon = '__base__/graphics/icons/logistic-chest-requester.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['small-electric-pole'] = {
            name = 'small-electric-pole',
            subgroup = 'energy-pipe-distribution',
            order = 'a[energy]-a[small-electric-pole]',
            icon_size = 64,
            place_result = 'small-electric-pole',
            icon = '__base__/graphics/icons/small-electric-pole.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['assembling-machine-1'] = {
            name = 'assembling-machine-1',
            subgroup = 'production-machine',
            order = 'a[assembling-machine-1]',
            icon_size = 64,
            place_result = 'assembling-machine-1',
            icon = '__base__/graphics/icons/assembling-machine-1.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['fusion-reactor-equipment'] = {
            name = 'fusion-reactor-equipment',
            subgroup = 'equipment',
            order = 'a[energy-source]-b[fusion-reactor]',
            icon_size = 64,
            icon = '__base__/graphics/icons/fusion-reactor-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 1,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'fusion-reactor-equipment'
        },
        ['small-lamp'] = {
            name = 'small-lamp',
            subgroup = 'circuit-network',
            order = 'a[light]-a[small-lamp]',
            icon_size = 64,
            place_result = 'small-lamp',
            icon = '__base__/graphics/icons/small-lamp.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        battery = {
            type = 'item',
            icon = '__base__/graphics/icons/battery.png',
            icon_mipmaps = 4,
            order = 'h[battery]',
            icon_size = 64,
            subgroup = 'raw-material',
            stack_size = 200,
            name = 'battery'
        },
        ['artillery-turret'] = {
            name = 'artillery-turret',
            subgroup = 'defensive-structure',
            order = 'b[turret]-d[artillery-turret]-a[turret]',
            icon_size = 64,
            place_result = 'artillery-turret',
            icon = '__base__/graphics/icons/artillery-turret.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['crash-site-chest-1'] = {
            name = 'crash-site-chest-1',
            subgroup = 'crash-site',
            order = 'x[crash-site-chest]',
            icon_size = 64,
            place_result = 'crash-site-chest-1',
            icon = '__base__/graphics/icons/crash-site-chest.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['logistic-robot'] = {
            name = 'logistic-robot',
            subgroup = 'logistic-network',
            order = 'a[robot]-a[logistic-robot]',
            icon_size = 64,
            place_result = 'logistic-robot',
            icon = '__base__/graphics/icons/logistic-robot.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['item-unknown'] = {
            icon = '__core__/graphics/icons/unknown.png',
            type = 'item',
            icon_size = 64,
            stack_size = 1,
            flags = {'hidden'},
            name = 'item-unknown'
        },
        ['logistic-chest-passive-provider'] = {
            name = 'logistic-chest-passive-provider',
            subgroup = 'logistic-network',
            order = 'b[storage]-c[logistic-chest-passive-provider]',
            icon_size = 64,
            place_result = 'logistic-chest-passive-provider',
            icon = '__base__/graphics/icons/logistic-chest-passive-provider.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['constant-combinator'] = {
            name = 'constant-combinator',
            subgroup = 'circuit-network',
            order = 'c[combinators]-c[constant-combinator]',
            icon_size = 64,
            place_result = 'constant-combinator',
            icon = '__base__/graphics/icons/constant-combinator.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['burner-inserter'] = {
            name = 'burner-inserter',
            subgroup = 'inserter',
            order = 'a[burner-inserter]',
            icon_size = 64,
            place_result = 'burner-inserter',
            icon = '__base__/graphics/icons/burner-inserter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['refined-hazard-concrete'] = {
            name = 'refined-hazard-concrete',
            subgroup = 'terrain',
            order = 'b[concrete]-d[refined-hazard]',
            icon_size = 64,
            place_as_tile = {condition = {'water-tile'}, condition_size = 1, result = 'refined-hazard-concrete-left'},
            icon = '__base__/graphics/icons/refined-hazard-concrete.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        sulfur = {
            type = 'item',
            icon = '__base__/graphics/icons/sulfur.png',
            icon_mipmaps = 4,
            order = 'g[sulfur]',
            icon_size = 64,
            subgroup = 'raw-material',
            stack_size = 50,
            name = 'sulfur'
        },
        ['infinity-pipe'] = {
            name = 'infinity-pipe',
            subgroup = 'other',
            order = 'd[item]-o[infinity-pipe]',
            icon_size = 64,
            place_result = 'infinity-pipe',
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {{tint = {g = 0.5, r = 0.5, b = 1}, icon = '__base__/graphics/icons/pipe.png'}},
            flags = {'hidden'},
            type = 'item'
        },
        ['uranium-238'] = {
            type = 'item',
            icon = '__base__/graphics/icons/uranium-238.png',
            icon_mipmaps = 4,
            order = 'r[uranium-238]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 100,
            name = 'uranium-238'
        },
        ['wooden-chest'] = {
            name = 'wooden-chest',
            subgroup = 'storage',
            order = 'a[items]-a[wooden-chest]',
            icon_size = 64,
            place_result = 'wooden-chest',
            icon = '__base__/graphics/icons/wooden-chest.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['crash-site-lab-broken'] = {
            name = 'crash-site-lab-broken',
            subgroup = 'crash-site',
            order = 'x[crash-site-lab-broken]',
            icon_size = 64,
            place_result = 'crash-site-lab-broken',
            icon = '__base__/graphics/icons/crash-site-lab-broken.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        wood = {
            name = 'wood',
            subgroup = 'raw-resource',
            order = 'a[wood]',
            icon_size = 64,
            fuel_value = '2MJ',
            icon_mipmaps = 4,
            fuel_category = 'chemical',
            type = 'item',
            stack_size = 100,
            icon = '__base__/graphics/icons/wood.png'
        },
        explosives = {
            type = 'item',
            icon = '__base__/graphics/icons/explosives.png',
            icon_mipmaps = 4,
            order = 'j[explosives]',
            icon_size = 64,
            subgroup = 'raw-material',
            stack_size = 50,
            name = 'explosives'
        },
        ['water-barrel'] = {
            name = 'water-barrel',
            subgroup = 'fill-barrel',
            order = 'b[water-barrel]',
            icon_size = 64,
            localised_name = {'item-name.filled-barrel', {'fluid-name.water'}},
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {
                {icon_size = 64, icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png', icon_mipmaps = 4},
                {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-side-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.34, r = 0, a = 0.75, b = 0.6}
                }, {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-hoop-top-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.7, r = 0.7, a = 0.75, b = 0.7}
                }
            },
            type = 'item'
        },
        ['rail-signal'] = {
            name = 'rail-signal',
            subgroup = 'train-transport',
            order = 'a[train-system]-d[rail-signal]',
            icon_size = 64,
            place_result = 'rail-signal',
            icon = '__base__/graphics/icons/rail-signal.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['lubricant-barrel'] = {
            name = 'lubricant-barrel',
            subgroup = 'fill-barrel',
            order = 'b[lubricant-barrel]',
            icon_size = 64,
            localised_name = {'item-name.filled-barrel', {'fluid-name.lubricant'}},
            icon_mipmaps = 4,
            stack_size = 10,
            icons = {
                {icon_size = 64, icon = '__base__/graphics/icons/fluid/barreling/empty-barrel.png', icon_mipmaps = 4},
                {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-side-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.32, r = 0.15, a = 0.75, b = 0.03}
                }, {
                    icon_size = 64,
                    icon = '__base__/graphics/icons/fluid/barreling/barrel-hoop-top-mask.png',
                    icon_mipmaps = 4,
                    tint = {g = 0.75, r = 0.43, a = 0.75, b = 0.31}
                }
            },
            type = 'item'
        },
        ['uranium-ore'] = {
            name = 'uranium-ore',
            subgroup = 'raw-resource',
            order = 'g[uranium-ore]',
            icon_size = 64,
            icon = '__base__/graphics/icons/uranium-ore.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item',
            pictures = {
                {filename = '__base__/graphics/icons/uranium-ore.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/uranium-ore-1.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/uranium-ore-2.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/uranium-ore-3.png', size = 64, scale = 0.25, mipmap_count = 4}
            }
        },
        ['uranium-fuel-cell'] = {
            burnt_result = 'used-up-uranium-fuel-cell',
            name = 'uranium-fuel-cell',
            subgroup = 'intermediate-product',
            order = 'r[uranium-processing]-a[uranium-fuel-cell]',
            icon_size = 64,
            fuel_value = '8GJ',
            icon_mipmaps = 4,
            fuel_category = 'nuclear',
            type = 'item',
            stack_size = 50,
            icon = '__base__/graphics/icons/uranium-fuel-cell.png'
        },
        substation = {
            name = 'substation',
            subgroup = 'energy-pipe-distribution',
            order = 'a[energy]-d[substation]',
            icon_size = 64,
            place_result = 'substation',
            icon = '__base__/graphics/icons/substation.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        lab = {
            name = 'lab',
            subgroup = 'production-machine',
            order = 'g[lab]',
            icon_size = 64,
            place_result = 'lab',
            icon = '__base__/graphics/icons/lab.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['underground-belt'] = {
            name = 'underground-belt',
            subgroup = 'belt',
            order = 'b[underground-belt]-a[underground-belt]',
            icon_size = 64,
            place_result = 'underground-belt',
            icon = '__base__/graphics/icons/underground-belt.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['flying-robot-frame'] = {
            type = 'item',
            icon = '__base__/graphics/icons/flying-robot-frame.png',
            icon_mipmaps = 4,
            order = 'l[flying-robot-frame]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 50,
            name = 'flying-robot-frame'
        },
        ['uranium-235'] = {
            type = 'item',
            icon = '__base__/graphics/icons/uranium-235.png',
            icon_mipmaps = 4,
            order = 'r[uranium-235]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 100,
            name = 'uranium-235'
        },
        ['copper-cable'] = {
            name = 'copper-cable',
            subgroup = 'intermediate-product',
            order = 'a[copper-cable]',
            icon_size = 64,
            wire_count = 1,
            icon = '__base__/graphics/icons/copper-cable.png',
            icon_mipmaps = 4,
            stack_size = 200,
            type = 'item'
        },
        ['storage-tank'] = {
            name = 'storage-tank',
            subgroup = 'storage',
            order = 'b[fluid]-a[storage-tank]',
            icon_size = 64,
            place_result = 'storage-tank',
            icon = '__base__/graphics/icons/storage-tank.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['stone-wall'] = {
            name = 'stone-wall',
            subgroup = 'defensive-structure',
            order = 'a[stone-wall]-a[stone-wall]',
            icon_size = 64,
            place_result = 'stone-wall',
            icon = '__base__/graphics/icons/wall.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['steam-turbine'] = {
            name = 'steam-turbine',
            subgroup = 'energy',
            order = 'f[nuclear-energy]-d[steam-turbine]',
            icon_size = 64,
            place_result = 'steam-turbine',
            icon = '__base__/graphics/icons/steam-turbine.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['stone-brick'] = {
            name = 'stone-brick',
            subgroup = 'terrain',
            order = 'a[stone-brick]',
            icon_size = 64,
            place_as_tile = {condition = {'water-tile'}, condition_size = 1, result = 'stone-path'},
            icon = '__base__/graphics/icons/stone-brick.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        stone = {
            name = 'stone',
            subgroup = 'raw-resource',
            order = 'd[stone]',
            icon_size = 64,
            icon = '__base__/graphics/icons/stone.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item',
            pictures = {
                {filename = '__base__/graphics/icons/stone.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/stone-1.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/stone-2.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/stone-3.png', size = 64, scale = 0.25, mipmap_count = 4}
            }
        },
        ['steel-plate'] = {
            type = 'item',
            icon = '__base__/graphics/icons/steel-plate.png',
            icon_mipmaps = 4,
            order = 'd[steel-plate]',
            icon_size = 64,
            subgroup = 'raw-material',
            stack_size = 100,
            name = 'steel-plate'
        },
        ['steel-furnace'] = {
            name = 'steel-furnace',
            subgroup = 'smelting-machine',
            order = 'b[steel-furnace]',
            icon_size = 64,
            place_result = 'steel-furnace',
            icon = '__base__/graphics/icons/steel-furnace.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        pipe = {
            name = 'pipe',
            subgroup = 'energy-pipe-distribution',
            order = 'a[pipe]-a[pipe]',
            icon_size = 64,
            place_result = 'pipe',
            icon = '__base__/graphics/icons/pipe.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['steel-chest'] = {
            name = 'steel-chest',
            subgroup = 'storage',
            order = 'a[items]-c[steel-chest]',
            icon_size = 64,
            place_result = 'steel-chest',
            icon = '__base__/graphics/icons/steel-chest.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['rocket-control-unit'] = {
            type = 'item',
            icon = '__base__/graphics/icons/rocket-control-unit.png',
            icon_mipmaps = 4,
            order = 'n[rocket-control-unit]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 10,
            name = 'rocket-control-unit'
        },
        ['oil-refinery'] = {
            name = 'oil-refinery',
            subgroup = 'production-machine',
            order = 'd[refinery]',
            icon_size = 64,
            place_result = 'oil-refinery',
            icon = '__base__/graphics/icons/oil-refinery.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['stone-furnace'] = {
            name = 'stone-furnace',
            subgroup = 'smelting-machine',
            order = 'a[stone-furnace]',
            icon_size = 64,
            place_result = 'stone-furnace',
            icon = '__base__/graphics/icons/stone-furnace.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        pump = {
            name = 'pump',
            subgroup = 'energy-pipe-distribution',
            order = 'b[pipe]-c[pump]',
            icon_size = 64,
            place_result = 'pump',
            icon = '__base__/graphics/icons/pump.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['fast-loader'] = {
            name = 'fast-loader',
            subgroup = 'belt',
            order = 'd[loader]-b[fast-loader]',
            icon_size = 64,
            place_result = 'fast-loader',
            icon = '__base__/graphics/icons/fast-loader.png',
            icon_mipmaps = 4,
            stack_size = 50,
            flags = {'hidden'},
            type = 'item'
        },
        ['solid-fuel'] = {
            fuel_top_speed_multiplier = 1.05,
            subgroup = 'raw-material',
            order = 'c[solid-fuel]',
            icon_size = 64,
            type = 'item',
            fuel_value = '12MJ',
            icon_mipmaps = 4,
            stack_size = 50,
            fuel_acceleration_multiplier = 1.2,
            name = 'solid-fuel',
            icon = '__base__/graphics/icons/solid-fuel.png',
            fuel_category = 'chemical'
        },
        ['long-handed-inserter'] = {
            name = 'long-handed-inserter',
            subgroup = 'inserter',
            order = 'c[long-handed-inserter]',
            icon_size = 64,
            place_result = 'long-handed-inserter',
            icon = '__base__/graphics/icons/long-handed-inserter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['personal-roboport-mk2-equipment'] = {
            name = 'personal-roboport-mk2-equipment',
            localised_description = {'item-description.personal-roboport-equipment'},
            order = 'e[robotics]-b[personal-roboport-mk2-equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/personal-roboport-mk2-equipment.png',
            icon_mipmaps = 4,
            type = 'item',
            default_request_amount = 1,
            subgroup = 'equipment',
            stack_size = 20,
            placed_as_equipment_result = 'personal-roboport-mk2-equipment'
        },
        satellite = {
            name = 'satellite',
            subgroup = 'intermediate-product',
            order = 'm[satellite]',
            icon_size = 64,
            rocket_launch_product = {'space-science-pack', 1000},
            icon = '__base__/graphics/icons/satellite.png',
            icon_mipmaps = 4,
            stack_size = 1,
            type = 'item'
        },
        ['rocket-silo'] = {
            name = 'rocket-silo',
            subgroup = 'defensive-structure',
            order = 'e[rocket-silo]',
            icon_size = 64,
            place_result = 'rocket-silo',
            icon = '__base__/graphics/icons/rocket-silo.png',
            icon_mipmaps = 4,
            stack_size = 1,
            type = 'item'
        },
        roboport = {
            name = 'roboport',
            subgroup = 'logistic-network',
            order = 'c[signal]-a[roboport]',
            icon_size = 64,
            place_result = 'roboport',
            icon = '__base__/graphics/icons/roboport.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['refined-concrete'] = {
            name = 'refined-concrete',
            subgroup = 'terrain',
            order = 'b[concrete]-c[refined]',
            icon_size = 64,
            place_as_tile = {condition = {'water-tile'}, condition_size = 1, result = 'refined-concrete'},
            icon = '__base__/graphics/icons/refined-concrete.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['rail-chain-signal'] = {
            name = 'rail-chain-signal',
            subgroup = 'train-transport',
            order = 'a[train-system]-e[rail-signal-chain]',
            icon_size = 64,
            place_result = 'rail-chain-signal',
            icon = '__base__/graphics/icons/rail-chain-signal.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['burner-generator'] = {
            name = 'burner-generator',
            subgroup = 'other',
            order = 't[item]-o[burner-generator]',
            icon_size = 64,
            place_result = 'burner-generator',
            icon = '__base__/graphics/icons/steam-engine.png',
            icon_mipmaps = 4,
            stack_size = 10,
            flags = {'hidden'},
            type = 'item'
        },
        ['express-loader'] = {
            name = 'express-loader',
            subgroup = 'belt',
            order = 'd[loader]-c[express-loader]',
            icon_size = 64,
            place_result = 'express-loader',
            icon = '__base__/graphics/icons/express-loader.png',
            icon_mipmaps = 4,
            stack_size = 50,
            flags = {'hidden'},
            type = 'item'
        },
        ['advanced-circuit'] = {
            type = 'item',
            icon = '__base__/graphics/icons/advanced-circuit.png',
            icon_mipmaps = 4,
            order = 'f[advanced-circuit]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 200,
            name = 'advanced-circuit'
        },
        ['low-density-structure'] = {
            type = 'item',
            icon = '__base__/graphics/icons/low-density-structure.png',
            icon_mipmaps = 4,
            order = 'o[low-density-structure]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 10,
            name = 'low-density-structure'
        },
        ['copper-plate'] = {
            type = 'item',
            icon = '__base__/graphics/icons/copper-plate.png',
            icon_mipmaps = 4,
            order = 'c[copper-plate]',
            icon_size = 64,
            subgroup = 'raw-material',
            stack_size = 100,
            name = 'copper-plate'
        },
        ['exoskeleton-equipment'] = {
            name = 'exoskeleton-equipment',
            subgroup = 'equipment',
            order = 'd[exoskeleton]-a[exoskeleton-equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/exoskeleton-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 5,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'exoskeleton-equipment'
        },
        pumpjack = {
            name = 'pumpjack',
            subgroup = 'extraction-machine',
            order = 'b[fluids]-b[pumpjack]',
            icon_size = 64,
            place_result = 'pumpjack',
            icon = '__base__/graphics/icons/pumpjack.png',
            icon_mipmaps = 4,
            stack_size = 20,
            type = 'item'
        },
        ['steam-engine'] = {
            name = 'steam-engine',
            subgroup = 'energy',
            order = 'b[steam-power]-b[steam-engine]',
            icon_size = 64,
            place_result = 'steam-engine',
            icon = '__base__/graphics/icons/steam-engine.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['player-port'] = {
            name = 'player-port',
            subgroup = 'defensive-structure',
            order = 'z[not-used]',
            icon_size = 64,
            place_result = 'player-port',
            icon = '__base__/graphics/icons/player-port.png',
            icon_mipmaps = 4,
            stack_size = 50,
            flags = {'hidden'},
            type = 'item'
        },
        ['plastic-bar'] = {
            type = 'item',
            icon = '__base__/graphics/icons/plastic-bar.png',
            icon_mipmaps = 4,
            order = 'f[plastic-bar]',
            icon_size = 64,
            subgroup = 'raw-material',
            stack_size = 100,
            name = 'plastic-bar'
        },
        ['express-underground-belt'] = {
            name = 'express-underground-belt',
            subgroup = 'belt',
            order = 'b[underground-belt]-c[express-underground-belt]',
            icon_size = 64,
            place_result = 'express-underground-belt',
            icon = '__base__/graphics/icons/express-underground-belt.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['electric-furnace'] = {
            name = 'electric-furnace',
            subgroup = 'smelting-machine',
            order = 'c[electric-furnace]',
            icon_size = 64,
            place_result = 'electric-furnace',
            icon = '__base__/graphics/icons/electric-furnace.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['offshore-pump'] = {
            name = 'offshore-pump',
            subgroup = 'extraction-machine',
            order = 'b[fluids]-a[offshore-pump]',
            icon_size = 64,
            place_result = 'offshore-pump',
            icon = '__base__/graphics/icons/offshore-pump.png',
            icon_mipmaps = 4,
            stack_size = 20,
            type = 'item'
        },
        ['nuclear-fuel'] = {
            fuel_top_speed_multiplier = 1.15,
            subgroup = 'intermediate-product',
            order = 'q[uranium-rocket-fuel]',
            icon_size = 64,
            type = 'item',
            fuel_value = '1.21GJ',
            icon_mipmaps = 4,
            stack_size = 1,
            fuel_acceleration_multiplier = 2.5,
            name = 'nuclear-fuel',
            icon = '__base__/graphics/icons/nuclear-fuel.png',
            fuel_category = 'chemical'
        },
        ['logistic-chest-buffer'] = {
            name = 'logistic-chest-buffer',
            subgroup = 'logistic-network',
            order = 'b[storage]-d[logistic-chest-buffer]',
            icon_size = 64,
            place_result = 'logistic-chest-buffer',
            icon = '__base__/graphics/icons/logistic-chest-buffer.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        loader = {
            name = 'loader',
            subgroup = 'belt',
            order = 'd[loader]-a[basic-loader]',
            icon_size = 64,
            place_result = 'loader',
            icon = '__base__/graphics/icons/loader.png',
            icon_mipmaps = 4,
            stack_size = 50,
            flags = {'hidden'},
            type = 'item'
        },
        gate = {
            name = 'gate',
            subgroup = 'defensive-structure',
            order = 'a[wall]-b[gate]',
            icon_size = 64,
            place_result = 'gate',
            icon = '__base__/graphics/icons/gate.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['infinity-chest'] = {
            name = 'infinity-chest',
            subgroup = 'other',
            order = 'c[item]-o[infinity-chest]',
            icon_size = 64,
            place_result = 'infinity-chest',
            icon = '__base__/graphics/icons/infinity-chest.png',
            icon_mipmaps = 4,
            stack_size = 10,
            flags = {'hidden'},
            type = 'item'
        },
        ['heat-pipe'] = {
            name = 'heat-pipe',
            subgroup = 'energy',
            order = 'f[nuclear-energy]-b[heat-pipe]',
            icon_size = 64,
            place_result = 'heat-pipe',
            icon = '__base__/graphics/icons/heat-pipe.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['copper-ore'] = {
            name = 'copper-ore',
            subgroup = 'raw-resource',
            order = 'f[copper-ore]',
            icon_size = 64,
            icon = '__base__/graphics/icons/copper-ore.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item',
            pictures = {
                {filename = '__base__/graphics/icons/copper-ore.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/copper-ore-1.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/copper-ore-2.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/copper-ore-3.png', size = 64, scale = 0.25, mipmap_count = 4}
            }
        },
        ['heat-interface'] = {
            name = 'heat-interface',
            subgroup = 'other',
            order = 'b[heat-interface]',
            icon_size = 64,
            place_result = 'heat-interface',
            icon = '__base__/graphics/icons/heat-interface.png',
            icon_mipmaps = 4,
            stack_size = 20,
            flags = {'hidden'},
            type = 'item'
        },
        ['hazard-concrete'] = {
            name = 'hazard-concrete',
            subgroup = 'terrain',
            order = 'b[concrete]-b[hazard]',
            icon_size = 64,
            place_as_tile = {condition = {'water-tile'}, condition_size = 1, result = 'hazard-concrete-left'},
            icon = '__base__/graphics/icons/hazard-concrete.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['crash-site-lab-repaired'] = {
            name = 'crash-site-lab-repaired',
            subgroup = 'crash-site',
            order = 'x[crash-site-lab-repaired]',
            icon_size = 64,
            place_result = 'crash-site-lab-repaired',
            icon = '__base__/graphics/icons/crash-site-lab-repaired.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['iron-gear-wheel'] = {
            type = 'item',
            icon = '__base__/graphics/icons/iron-gear-wheel.png',
            icon_mipmaps = 4,
            order = 'c[iron-gear-wheel]',
            icon_size = 64,
            subgroup = 'intermediate-product',
            stack_size = 100,
            name = 'iron-gear-wheel'
        },
        ['transport-belt'] = {
            name = 'transport-belt',
            subgroup = 'belt',
            order = 'a[transport-belt]-a[transport-belt]',
            icon_size = 64,
            place_result = 'transport-belt',
            icon = '__base__/graphics/icons/transport-belt.png',
            icon_mipmaps = 4,
            stack_size = 100,
            type = 'item'
        },
        ['energy-shield-mk2-equipment'] = {
            name = 'energy-shield-mk2-equipment',
            localised_description = {'item-description.energy-shield-equipment'},
            order = 'a[shield]-b[energy-shield-equipment-mk2]',
            icon_size = 64,
            icon = '__base__/graphics/icons/energy-shield-mk2-equipment.png',
            icon_mipmaps = 4,
            type = 'item',
            default_request_amount = 5,
            subgroup = 'military-equipment',
            stack_size = 20,
            placed_as_equipment_result = 'energy-shield-mk2-equipment'
        },
        beacon = {
            name = 'beacon',
            subgroup = 'module',
            order = 'a[beacon]',
            icon_size = 64,
            place_result = 'beacon',
            icon = '__base__/graphics/icons/beacon.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['flamethrower-turret'] = {
            name = 'flamethrower-turret',
            subgroup = 'defensive-structure',
            order = 'b[turret]-c[flamethrower-turret]',
            icon_size = 64,
            place_result = 'flamethrower-turret',
            icon = '__base__/graphics/icons/flamethrower-turret.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['chemical-plant'] = {
            name = 'chemical-plant',
            subgroup = 'production-machine',
            order = 'e[chemical-plant]',
            icon_size = 64,
            place_result = 'chemical-plant',
            icon = '__base__/graphics/icons/chemical-plant.png',
            icon_mipmaps = 4,
            stack_size = 10,
            type = 'item'
        },
        ['personal-roboport-equipment'] = {
            name = 'personal-roboport-equipment',
            subgroup = 'equipment',
            order = 'e[robotics]-a[personal-roboport-equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/personal-roboport-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 1,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'personal-roboport-equipment'
        },
        ['express-splitter'] = {
            name = 'express-splitter',
            subgroup = 'belt',
            order = 'c[splitter]-c[express-splitter]',
            icon_size = 64,
            place_result = 'express-splitter',
            icon = '__base__/graphics/icons/express-splitter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        coal = {
            name = 'coal',
            subgroup = 'raw-resource',
            dark_background_icon = '__base__/graphics/icons/coal-dark-background.png',
            icon_size = 64,
            type = 'item',
            fuel_value = '4MJ',
            icon_mipmaps = 4,
            stack_size = 50,
            fuel_category = 'chemical',
            pictures = {
                {filename = '__base__/graphics/icons/coal.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/coal-1.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/coal-2.png', size = 64, scale = 0.25, mipmap_count = 4},
                {filename = '__base__/graphics/icons/coal-3.png', size = 64, scale = 0.25, mipmap_count = 4}
            },
            order = 'b[coal]',
            icon = '__base__/graphics/icons/coal.png'
        },
        radar = {
            name = 'radar',
            subgroup = 'defensive-structure',
            order = 'd[radar]-a[radar]',
            icon_size = 64,
            place_result = 'radar',
            icon = '__base__/graphics/icons/radar.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        },
        ['crash-site-generator'] = {
            name = 'crash-site-generator',
            subgroup = 'crash-site',
            order = 'x[crash-site-generator]',
            icon_size = 64,
            place_result = 'crash-site-generator',
            icon = '__base__/graphics/icons/crash-site-generator.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['discharge-defense-equipment'] = {
            name = 'discharge-defense-equipment',
            subgroup = 'military-equipment',
            order = 'b[active-defense]-b[discharge-defense-equipment]-a[equipment]',
            icon_size = 64,
            icon = '__base__/graphics/icons/discharge-defense-equipment.png',
            icon_mipmaps = 4,
            default_request_amount = 1,
            type = 'item',
            stack_size = 20,
            placed_as_equipment_result = 'discharge-defense-equipment'
        },
        ['crash-site-electric-pole'] = {
            name = 'crash-site-electric-pole',
            subgroup = 'crash-site',
            order = 'x[crash-site-electric-pole]',
            icon_size = 64,
            place_result = 'crash-site-electric-pole',
            icon = '__base__/graphics/icons/crash-site-electric-pole.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['crash-site-assembling-machine-2-repaired'] = {
            name = 'crash-site-assembling-machine-2-repaired',
            subgroup = 'crash-site',
            order = 'x[crash-site-assembling-machine-2-repaired]',
            icon_size = 64,
            place_result = 'crash-site-assembling-machine-2-repaired',
            icon = '__base__/graphics/icons/crash-site-assembling-machine-2-repaired.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['crash-site-assembling-machine-2-broken'] = {
            name = 'crash-site-assembling-machine-2-broken',
            subgroup = 'crash-site',
            order = 'x[crash-site-assembling-machine-2-broken]',
            icon_size = 64,
            place_result = 'crash-site-assembling-machine-2-broken',
            icon = '__base__/graphics/icons/crash-site-assembling-machine-2-broken.png',
            icon_mipmaps = 4,
            stack_size = 1,
            flags = {'hidden'},
            type = 'item'
        },
        ['fast-inserter'] = {
            name = 'fast-inserter',
            subgroup = 'inserter',
            order = 'd[fast-inserter]',
            icon_size = 64,
            place_result = 'fast-inserter',
            icon = '__base__/graphics/icons/fast-inserter.png',
            icon_mipmaps = 4,
            stack_size = 50,
            type = 'item'
        }
    };
    return _;
end
