do
    local _ = {
        'item-entity', 'group-attack-achievement', 'autoplace-control', 'optimized-particle', 'unit', 'pipe-to-ground',
        'arrow', 'energy-shield-equipment', 'character-corpse', 'loader-1x1', 'character', 'market', 'font', 'ammo',
        'active-defense-equipment', 'map-settings', 'module', 'decider-combinator', 'arithmetic-combinator',
        'highlight-box', 'item-with-label', 'train-path-achievement', 'lamp', 'land-mine', 'capsule',
        'build-entity-achievement', 'programmable-speaker', 'electric-energy-interface', 'artillery-projectile',
        'damage-type', 'battery-equipment', 'projectile', 'rail-planner', 'corpse', 'fluid',
        'deliver-by-robots-achievement', 'leaf-particle', 'selection-tool', 'utility-sounds', 'smoke', 'electric-pole',
        'flame-thrower-explosion', 'ambient-sound', 'mining-tool', 'construction-robot', 'item-subgroup', 'rocket-silo',
        'train-stop', 'splitter', 'solar-panel-equipment', 'accumulator', 'rail-remnants', 'simple-entity-with-force',
        'solar-panel', 'ammo-category', 'inserter', 'resource', 'armor', 'deconstruct-with-robots-achievement',
        'stream', 'fluid-wagon', 'underground-belt', 'boiler', 'particle', 'resource-category', 'kill-achievement',
        'logistic-container', 'dont-use-entity-in-energy-production-achievement', 'belt-immunity-equipment', 'shortcut',
        'god-controller', 'power-switch', 'item-with-tags', 'editor-controller', 'combat-robot', 'tile-ghost',
        'wind-sound', 'wall', 'virtual-signal', 'spidertron-remote', 'dont-build-entity-achievement', 'locomotive',
        'utility-sprites', 'sticker', 'combat-robot-count', 'electric-turret', 'artillery-turret', 'unit-spawner',
        'turret', 'research-achievement', 'flying-text', 'generator-equipment', 'blueprint', 'beam', 'map-gen-presets',
        'custom-input', 'trivial-smoke', 'constant-combinator', 'generator', 'rail-chain-signal', 'spider-leg', 'tree',
        'produce-achievement', 'equipment-grid', 'infinity-pipe', 'fluid-turret', 'spider-vehicle', 'gun', 'tool',
        'tutorial', 'achievement', 'tile', 'technology', 'container', 'player-port', 'fire', 'ammo-turret',
        'spectator-controller', 'rail-signal', 'pump', 'utility-constants', 'furnace', 'roboport-equipment', 'lab',
        'assembling-machine', 'sprite', 'explosion', 'heat-interface', 'storage-tank', 'smoke-with-trigger', 'item',
        'simple-entity-with-owner', 'simple-entity', 'rocket-silo-rocket-shadow', 'rocket-silo-rocket', 'pipe',
        'equipment-category', 'roboport', 'repair-tool', 'recipe-category', 'item-request-proxy',
        'movement-bonus-equipment', 'reactor', 'trigger-target-type', 'deconstructible-tile-proxy',
        'produce-per-hour-achievement', 'artillery-wagon', 'straight-rail', 'player-damaged-achievement',
        'particle-source', 'burner-generator', 'optimized-decorative', 'fish', 'module-category', 'offshore-pump',
        'item-with-inventory', 'noise-expression', 'cliff', 'blueprint-book', 'dont-craft-manually-achievement',
        'night-vision-equipment', 'recipe', 'gui-style', 'mouse-cursor', 'mining-drill', 'logistic-robot',
        'infinity-container', 'loader', 'noise-layer', 'item-with-entity-data', 'artillery-flare', 'tile-effect',
        'heat-pipe', 'deconstruction-item', 'transport-belt', 'entity-ghost', 'beacon', 'gate', 'fuel-category',
        'finish-the-game-achievement', 'speech-bubble', 'item-group', 'radar', 'curved-rail', 'copy-paste-tool',
        'construct-with-robots-achievement', 'upgrade-item', 'car', 'cargo-wagon'
    };
    return _;
end
