do
    local _ = {
        ['programmable-speaker'] = {
            circuit_connector_sprites = {
                wire_pins_shadow = {
                    draw_as_shadow = true,
                    x = 140,
                    height = 54,
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04d-wire-shadow-sequence.png',
                    width = 70,
                    scale = 0.5,
                    shift = {0.15625, -0.125},
                    priority = 'low',
                    y = 108
                },
                led_red = {
                    y = 92,
                    x = 96,
                    height = 46,
                    shift = {0, -0.25},
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04i-red-LED-sequence.png',
                    width = 48,
                    priority = 'low',
                    scale = 0.5
                },
                blue_led_light_offset = {0.03125, 0.03125},
                led_blue_off = {
                    y = 88,
                    x = 92,
                    height = 44,
                    shift = {0, -0.25},
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04f-blue-LED-off-sequence.png',
                    width = 46,
                    priority = 'low',
                    scale = 0.5
                },
                connector_main = {
                    y = 100,
                    x = 104,
                    height = 50,
                    shift = {0, -0.21875},
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04a-base-sequence.png',
                    width = 52,
                    priority = 'low',
                    scale = 0.5
                },
                wire_pins = {
                    y = 116,
                    x = 124,
                    height = 58,
                    shift = {0, -0.25},
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04c-wire-sequence.png',
                    width = 62,
                    priority = 'low',
                    scale = 0.5
                },
                connector_shadow = {
                    draw_as_shadow = true,
                    x = 124,
                    height = 46,
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04b-base-shadow-sequence.png',
                    width = 62,
                    scale = 0.5,
                    shift = {0.21875, -0.140625},
                    priority = 'low',
                    y = 92
                },
                led_green = {
                    y = 92,
                    x = 96,
                    height = 46,
                    shift = {0, -0.25},
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04h-green-LED-sequence.png',
                    width = 48,
                    priority = 'low',
                    scale = 0.5
                },
                led_light = {intensity = 0.8, size = 0.9},
                red_green_led_light_offset = {0.015625, -0.140625},
                led_blue = {
                    y = 120,
                    x = 120,
                    height = 60,
                    shift = {0, -0.25},
                    filename = '__base__/graphics/entity/circuit-connector/hr-ccm-universal-04e-blue-LED-on-sequence.png',
                    width = 60,
                    priority = 'low',
                    scale = 0.5
                }
            },
            vehicle_impact_sound = 0,
            sprite = {
                layers = {
                    {
                        height = 89,
                        shift = {-0.0625, -1.234375},
                        filename = '__base__/graphics/entity/programmable-speaker/programmable-speaker.png',
                        width = 30,
                        priority = 'extra-high',
                        hr_version = {
                            height = 178,
                            shift = {-0.0703125, -1.234375},
                            filename = '__base__/graphics/entity/programmable-speaker/hr-programmable-speaker.png',
                            width = 59,
                            priority = 'extra-high',
                            scale = 0.5
                        }
                    }, {
                        draw_as_shadow = true,
                        height = 25,
                        shift = {1.640625, -0.078125},
                        filename = '__base__/graphics/entity/programmable-speaker/programmable-speaker-shadow.png',
                        width = 119,
                        priority = 'extra-high',
                        hr_version = {
                            draw_as_shadow = true,
                            height = 50,
                            shift = {1.6484375, -0.09375},
                            filename = '__base__/graphics/entity/programmable-speaker/hr-programmable-speaker-shadow.png',
                            width = 237,
                            priority = 'extra-high',
                            scale = 0.5
                        }
                    }
                }
            },
            icon_size = 64,
            energy_source = {type = 'electric', usage_priority = 'secondary-input'},
            circuit_wire_max_distance = 9,
            minable = {mining_time = 0.1, result = 'programmable-speaker'},
            icon_mipmaps = 4,
            energy_usage_per_tick = '2KW',
            flags = {'placeable-neutral', 'player-creation'},
            max_health = 150,
            water_reflection = {
                rotate = false,
                orientation_to_variation = false,
                pictures = {
                    shift = {0, 1.40625},
                    height = 24,
                    variation_count = 1,
                    filename = '__base__/graphics/entity/programmable-speaker/programmable-speaker-reflection.png',
                    width = 12,
                    priority = 'extra-high',
                    scale = 5
                }
            },
            name = 'programmable-speaker',
            type = 'programmable-speaker',
            damaged_trigger_effect = {
                entity_name = 'spark-explosion',
                offsets = {{0, 1}},
                type = 'create-entity',
                damage_type_filters = 'fire',
                offset_deviation = {{-0.2, -2}, {0.2, 0.2}}
            },
            dying_explosion = 'programmable-speaker-explosion',
            maximum_polyphony = 10,
            open_sound = 0,
            circuit_wire_connection_point = {
                shadow = {green = {0.625, 0.171875}, red = {0.78125, 0.078125}},
                wire = {green = {0.359375, 0.03125}, red = {0.296875, -0.203125}}
            },
            audible_distance_modifier = 2,
            drawing_box = {{-0.5, -2.5}, {0.5, 0.3}},
            collision_box = {{-0.3, -0.3}, {0.3, 0.3}},
            selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
            instruments = {
                {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/alarm-1.ogg'}, name = 'alarm-1'},
                        {sound = {filename = '__base__/sound/programmable-speaker/alarm-2.ogg'}, name = 'alarm-2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/buzzer-1.ogg'}, name = 'buzzer-1'},
                        {sound = {filename = '__base__/sound/programmable-speaker/buzzer-2.ogg'}, name = 'buzzer-2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/buzzer-3.ogg'}, name = 'buzzer-3'},
                        {
                            sound = {filename = '__base__/sound/programmable-speaker/ring.ogg', preload = false},
                            name = 'ring'
                        },
                        {
                            sound = {filename = '__base__/sound/programmable-speaker/siren.ogg', preload = false},
                            name = 'siren'
                        }
                    },
                    name = 'alarms'
                }, {
                    notes = {
                        {sound = {filename = '__core__/sound/achievement-unlocked.ogg'}, name = 'achievement-unlocked'},
                        {sound = {filename = '__core__/sound/alert-destroyed.ogg'}, name = 'alert-destroyed'},
                        {sound = {filename = '__core__/sound/armor-insert.ogg'}, name = 'armor-insert'},
                        {sound = {filename = '__core__/sound/armor-remove.ogg'}, name = 'armor-remove'},
                        {sound = {filename = '__core__/sound/cannot-build.ogg'}, name = 'cannot-build'},
                        {sound = {filename = '__core__/sound/console-message.ogg'}, name = 'console-message'},
                        {sound = {filename = '__core__/sound/crafting-finished.ogg'}, name = 'crafting-finished'},
                        {sound = {filename = '__core__/sound/game-lost.ogg'}, name = 'game-lost'},
                        {sound = {filename = '__core__/sound/game-won.ogg'}, name = 'game-won'},
                        {sound = {filename = '__core__/sound/gui-click.ogg'}, name = 'gui-click'},
                        {sound = {filename = '__core__/sound/list-box-click.ogg'}, name = 'gui-click-2'},
                        {sound = {filename = '__core__/sound/inventory-move.ogg'}, name = 'inventory-move'},
                        {sound = {filename = '__core__/sound/new-objective.ogg'}, name = 'new-objective'},
                        {sound = {filename = '__core__/sound/research-completed.ogg'}, name = 'research-completed'},
                        {sound = {filename = '__core__/sound/scenario-message.ogg'}, name = 'scenario-message'}
                    },
                    name = 'miscellaneous'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-01.ogg'}, name = 'kick-1'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-02.ogg'}, name = 'kick-2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-03.ogg'}, name = 'snare-1'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-04.ogg'}, name = 'snare-2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-05.ogg'}, name = 'snare-3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-06.ogg'}, name = 'hat-1'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-07.ogg'}, name = 'hat-2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-08.ogg'}, name = 'fx'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-09.ogg'}, name = 'high-q'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-10.ogg'}, name = 'perc-1'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-11.ogg'}, name = 'perc-2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-12.ogg'}, name = 'crash'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-13.ogg'}, name = 'reverse-cymbal'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-14.ogg'}, name = 'clap'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-15.ogg'}, name = 'shaker'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-16.ogg'}, name = 'cowbell'},
                        {sound = {filename = '__base__/sound/programmable-speaker/kit-17.ogg'}, name = 'triangle'}
                    },
                    name = 'drum-kit'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-01.ogg'}, name = 'F3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-02.ogg'}, name = 'F#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-03.ogg'}, name = 'G3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-04.ogg'}, name = 'G#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-05.ogg'}, name = 'A3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-06.ogg'}, name = 'A#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-07.ogg'}, name = 'B3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-08.ogg'}, name = 'C4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-09.ogg'}, name = 'C#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-10.ogg'}, name = 'D4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-11.ogg'}, name = 'D#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-12.ogg'}, name = 'E4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-13.ogg'}, name = 'F4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-14.ogg'}, name = 'F#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-15.ogg'}, name = 'G4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-16.ogg'}, name = 'G#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-17.ogg'}, name = 'A4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-18.ogg'}, name = 'A#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-19.ogg'}, name = 'B4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-20.ogg'}, name = 'C5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-21.ogg'}, name = 'C#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-22.ogg'}, name = 'D5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-23.ogg'}, name = 'D#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-24.ogg'}, name = 'E5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-25.ogg'}, name = 'F5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-26.ogg'}, name = 'F#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-27.ogg'}, name = 'G5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-28.ogg'}, name = 'G#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-29.ogg'}, name = 'A5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-30.ogg'}, name = 'A#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-31.ogg'}, name = 'B5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-32.ogg'}, name = 'C6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-33.ogg'}, name = 'C#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-34.ogg'}, name = 'D6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-35.ogg'}, name = 'D#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-36.ogg'}, name = 'E6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-37.ogg'}, name = 'F6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-38.ogg'}, name = 'F#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-39.ogg'}, name = 'G6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-40.ogg'}, name = 'G#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-41.ogg'}, name = 'A6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-42.ogg'}, name = 'A#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-43.ogg'}, name = 'B6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-44.ogg'}, name = 'C7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-45.ogg'}, name = 'C#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-46.ogg'}, name = 'D7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-47.ogg'}, name = 'D#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/piano1-48.ogg'}, name = 'E7'}
                    },
                    name = 'piano'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-01.ogg'}, name = 'F2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-02.ogg'}, name = 'F#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-03.ogg'}, name = 'G2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-04.ogg'}, name = 'G#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-05.ogg'}, name = 'A2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-06.ogg'}, name = 'A#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-07.ogg'}, name = 'B2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-08.ogg'}, name = 'C3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-09.ogg'}, name = 'C#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-10.ogg'}, name = 'D3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-11.ogg'}, name = 'D#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-12.ogg'}, name = 'E3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-13.ogg'}, name = 'F3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-14.ogg'}, name = 'F#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-15.ogg'}, name = 'G3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-16.ogg'}, name = 'G#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-17.ogg'}, name = 'A3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-18.ogg'}, name = 'A#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-19.ogg'}, name = 'B3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-20.ogg'}, name = 'C4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-21.ogg'}, name = 'C#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-22.ogg'}, name = 'D4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-23.ogg'}, name = 'D#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-24.ogg'}, name = 'E4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-25.ogg'}, name = 'F4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-26.ogg'}, name = 'F#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-27.ogg'}, name = 'G4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-28.ogg'}, name = 'G#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-29.ogg'}, name = 'A4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-30.ogg'}, name = 'A#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-31.ogg'}, name = 'B4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-32.ogg'}, name = 'C5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-33.ogg'}, name = 'C#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-34.ogg'}, name = 'D5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-35.ogg'}, name = 'D#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/bass-36.ogg'}, name = 'E5'}
                    },
                    name = 'bass'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-01.ogg'}, name = 'F2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-02.ogg'}, name = 'F#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-03.ogg'}, name = 'G2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-04.ogg'}, name = 'G#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-05.ogg'}, name = 'A2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-06.ogg'}, name = 'A#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-07.ogg'}, name = 'B2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-08.ogg'}, name = 'C3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-09.ogg'}, name = 'C#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-10.ogg'}, name = 'D3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-11.ogg'}, name = 'D#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-12.ogg'}, name = 'E3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-13.ogg'}, name = 'F3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-14.ogg'}, name = 'F#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-15.ogg'}, name = 'G3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-16.ogg'}, name = 'G#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-17.ogg'}, name = 'A3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-18.ogg'}, name = 'A#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-19.ogg'}, name = 'B3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-20.ogg'}, name = 'C4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-21.ogg'}, name = 'C#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-22.ogg'}, name = 'D4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-23.ogg'}, name = 'D#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-24.ogg'}, name = 'E4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-25.ogg'}, name = 'F4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-26.ogg'}, name = 'F#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-27.ogg'}, name = 'G4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-28.ogg'}, name = 'G#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-29.ogg'}, name = 'A4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-30.ogg'}, name = 'A#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-31.ogg'}, name = 'B4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-32.ogg'}, name = 'C5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-33.ogg'}, name = 'C#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-34.ogg'}, name = 'D5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-35.ogg'}, name = 'D#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/lead-36.ogg'}, name = 'E5'}
                    },
                    name = 'lead'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-01.ogg'}, name = 'F2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-02.ogg'}, name = 'F#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-03.ogg'}, name = 'G2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-04.ogg'}, name = 'G#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-05.ogg'}, name = 'A2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-06.ogg'}, name = 'A#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-07.ogg'}, name = 'B2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-08.ogg'}, name = 'C3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-09.ogg'}, name = 'C#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-10.ogg'}, name = 'D3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-11.ogg'}, name = 'D#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-12.ogg'}, name = 'E3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-13.ogg'}, name = 'F3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-14.ogg'}, name = 'F#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-15.ogg'}, name = 'G3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-16.ogg'}, name = 'G#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-17.ogg'}, name = 'A3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-18.ogg'}, name = 'A#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-19.ogg'}, name = 'B3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-20.ogg'}, name = 'C4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-21.ogg'}, name = 'C#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-22.ogg'}, name = 'D4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-23.ogg'}, name = 'D#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-24.ogg'}, name = 'E4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-25.ogg'}, name = 'F4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-26.ogg'}, name = 'F#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-27.ogg'}, name = 'G4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-28.ogg'}, name = 'G#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-29.ogg'}, name = 'A4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-30.ogg'}, name = 'A#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-31.ogg'}, name = 'B4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-32.ogg'}, name = 'C5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-33.ogg'}, name = 'C#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-34.ogg'}, name = 'D5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-35.ogg'}, name = 'D#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/saw-36.ogg'}, name = 'E5'}
                    },
                    name = 'saw'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/square-01.ogg'}, name = 'F2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-02.ogg'}, name = 'F#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-03.ogg'}, name = 'G2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-04.ogg'}, name = 'G#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-05.ogg'}, name = 'A2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-06.ogg'}, name = 'A#2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-07.ogg'}, name = 'B2'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-08.ogg'}, name = 'C3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-09.ogg'}, name = 'C#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-10.ogg'}, name = 'D3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-11.ogg'}, name = 'D#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-12.ogg'}, name = 'E3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-13.ogg'}, name = 'F3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-14.ogg'}, name = 'F#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-15.ogg'}, name = 'G3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-16.ogg'}, name = 'G#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-17.ogg'}, name = 'A3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-18.ogg'}, name = 'A#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-19.ogg'}, name = 'B3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-20.ogg'}, name = 'C4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-21.ogg'}, name = 'C#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-22.ogg'}, name = 'D4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-23.ogg'}, name = 'D#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-24.ogg'}, name = 'E4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-25.ogg'}, name = 'F4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-26.ogg'}, name = 'F#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-27.ogg'}, name = 'G4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-28.ogg'}, name = 'G#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-29.ogg'}, name = 'A4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-30.ogg'}, name = 'A#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-31.ogg'}, name = 'B4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-32.ogg'}, name = 'C5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-33.ogg'}, name = 'C#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-34.ogg'}, name = 'D5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-35.ogg'}, name = 'D#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/square-36.ogg'}, name = 'E5'}
                    },
                    name = 'square'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-01.ogg'}, name = 'F5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-02.ogg'}, name = 'F#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-03.ogg'}, name = 'G5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-04.ogg'}, name = 'G#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-05.ogg'}, name = 'A5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-06.ogg'}, name = 'A#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-07.ogg'}, name = 'B5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-08.ogg'}, name = 'C6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-09.ogg'}, name = 'C#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-10.ogg'}, name = 'D6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-11.ogg'}, name = 'D#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-12.ogg'}, name = 'E6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-13.ogg'}, name = 'F6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-14.ogg'}, name = 'F#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-15.ogg'}, name = 'G6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-16.ogg'}, name = 'G#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-17.ogg'}, name = 'A6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-18.ogg'}, name = 'A#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-19.ogg'}, name = 'B6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-20.ogg'}, name = 'C7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-21.ogg'}, name = 'C#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-22.ogg'}, name = 'D7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-23.ogg'}, name = 'D#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-24.ogg'}, name = 'E7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-25.ogg'}, name = 'F7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-26.ogg'}, name = 'F#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-27.ogg'}, name = 'G7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-28.ogg'}, name = 'G#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-29.ogg'}, name = 'A7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-30.ogg'}, name = 'A#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-31.ogg'}, name = 'B7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-32.ogg'}, name = 'C8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-33.ogg'}, name = 'C#8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-34.ogg'}, name = 'D8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-35.ogg'}, name = 'D#8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/celesta-36.ogg'}, name = 'E8'}
                    },
                    name = 'celesta'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-01.ogg'}, name = 'F5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-02.ogg'}, name = 'F#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-03.ogg'}, name = 'G5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-04.ogg'}, name = 'G#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-05.ogg'}, name = 'A5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-06.ogg'}, name = 'A#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-07.ogg'}, name = 'B5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-08.ogg'}, name = 'C6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-09.ogg'}, name = 'C#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-10.ogg'}, name = 'D6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-11.ogg'}, name = 'D#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-12.ogg'}, name = 'E6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-13.ogg'}, name = 'F6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-14.ogg'}, name = 'F#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-15.ogg'}, name = 'G6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-16.ogg'}, name = 'G#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-17.ogg'}, name = 'A6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-18.ogg'}, name = 'A#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-19.ogg'}, name = 'B6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-20.ogg'}, name = 'C7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-21.ogg'}, name = 'C#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-22.ogg'}, name = 'D7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-23.ogg'}, name = 'D#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-24.ogg'}, name = 'E7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-25.ogg'}, name = 'F7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-26.ogg'}, name = 'F#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-27.ogg'}, name = 'G7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-28.ogg'}, name = 'G#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-29.ogg'}, name = 'A7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-30.ogg'}, name = 'A#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-31.ogg'}, name = 'B7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-32.ogg'}, name = 'C8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-33.ogg'}, name = 'C#8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-34.ogg'}, name = 'D8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-35.ogg'}, name = 'D#8'},
                        {sound = {filename = '__base__/sound/programmable-speaker/vibraphone-36.ogg'}, name = 'E8'}
                    },
                    name = 'vibraphone'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-01.ogg'}, name = 'F4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-02.ogg'}, name = 'F#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-03.ogg'}, name = 'G4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-04.ogg'}, name = 'G#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-05.ogg'}, name = 'A4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-06.ogg'}, name = 'A#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-07.ogg'}, name = 'B4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-08.ogg'}, name = 'C5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-09.ogg'}, name = 'C#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-10.ogg'}, name = 'D5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-11.ogg'}, name = 'D#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-12.ogg'}, name = 'E5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-13.ogg'}, name = 'F5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-14.ogg'}, name = 'F#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-15.ogg'}, name = 'G5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-16.ogg'}, name = 'G#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-17.ogg'}, name = 'A5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-18.ogg'}, name = 'A#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-19.ogg'}, name = 'B5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-20.ogg'}, name = 'C6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-21.ogg'}, name = 'C#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-22.ogg'}, name = 'D6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-23.ogg'}, name = 'D#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-24.ogg'}, name = 'E6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-25.ogg'}, name = 'F6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-26.ogg'}, name = 'F#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-27.ogg'}, name = 'G6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-28.ogg'}, name = 'G#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-29.ogg'}, name = 'A6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-30.ogg'}, name = 'A#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-31.ogg'}, name = 'B6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-32.ogg'}, name = 'C7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-33.ogg'}, name = 'C#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-34.ogg'}, name = 'D7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-35.ogg'}, name = 'D#7'},
                        {sound = {filename = '__base__/sound/programmable-speaker/plucked-36.ogg'}, name = 'E7'}
                    },
                    name = 'plucked'
                }, {
                    notes = {
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-01.ogg'}, name = 'F3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-02.ogg'}, name = 'F#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-03.ogg'}, name = 'G3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-04.ogg'}, name = 'G#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-05.ogg'}, name = 'A3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-06.ogg'}, name = 'A#3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-07.ogg'}, name = 'B3'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-08.ogg'}, name = 'C4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-09.ogg'}, name = 'C#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-10.ogg'}, name = 'D4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-11.ogg'}, name = 'D#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-12.ogg'}, name = 'E4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-13.ogg'}, name = 'F4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-14.ogg'}, name = 'F#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-15.ogg'}, name = 'G4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-16.ogg'}, name = 'G#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-17.ogg'}, name = 'A4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-18.ogg'}, name = 'A#4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-19.ogg'}, name = 'B4'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-20.ogg'}, name = 'C5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-21.ogg'}, name = 'C#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-22.ogg'}, name = 'D5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-23.ogg'}, name = 'D#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-24.ogg'}, name = 'E5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-25.ogg'}, name = 'F5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-26.ogg'}, name = 'F#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-27.ogg'}, name = 'G5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-28.ogg'}, name = 'G#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-29.ogg'}, name = 'A5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-30.ogg'}, name = 'A#5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-31.ogg'}, name = 'B5'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-32.ogg'}, name = 'C6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-33.ogg'}, name = 'C#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-34.ogg'}, name = 'D6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-35.ogg'}, name = 'D#6'},
                        {sound = {filename = '__base__/sound/programmable-speaker/steel-drum-36.ogg'}, name = 'E6'}
                    },
                    name = 'steel-drum'
                }
            },
            icon = '__base__/graphics/icons/programmable-speaker.png',
            close_sound = 0,
            corpse = 'programmable-speaker-remnants'
        }
    };
    return _;
end
