do
    local _ = {
        ['rocket-silo-rocket'] = {
            rocket_flame_left_rotation = 0.0611,
            rocket_above_wires_slice_offset_from_center = -3,
            shadow_fade_out_start_ratio = 0.25,
            effects_fade_in_end_distance = 7.5,
            rocket_flame_right_animation = {
                filename = '__base__/graphics/entity/rocket-silo/10-jet-flame.png',
                line_length = 8,
                blend_mode = 'additive',
                frame_count = 8,
                width = 87,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-10-jet-flame.png',
                    line_length = 8,
                    blend_mode = 'additive',
                    frame_count = 8,
                    width = 172,
                    animation_speed = 0.5,
                    scale = 0.2116,
                    height = 256,
                    shift = {1.46875, 7.125},
                    priority = 'medium'
                },
                animation_speed = 0.5,
                scale = 0.4232,
                height = 128,
                shift = {1.484375, 7.125},
                priority = 'medium'
            },
            rocket_initial_offset = {0, 1.5},
            collision_box = {{-2, -7}, {2, 4}},
            flying_acceleration = 0.01,
            dying_explosion = 'massive-explosion',
            rocket_flame_left_animation = {
                filename = '__base__/graphics/entity/rocket-silo/10-jet-flame.png',
                line_length = 8,
                blend_mode = 'additive',
                frame_count = 8,
                width = 87,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-10-jet-flame.png',
                    line_length = 8,
                    blend_mode = 'additive',
                    frame_count = 8,
                    width = 172,
                    animation_speed = 0.5,
                    scale = 0.198375,
                    height = 256,
                    shift = {-1.8125, 6.59375},
                    priority = 'medium'
                },
                animation_speed = 0.5,
                scale = 0.39675,
                height = 128,
                shift = {-1.796875, 6.59375},
                priority = 'medium'
            },
            type = 'rocket-silo-rocket',
            full_render_layer_switch_distance = 9,
            effects_fade_in_start_distance = 4.5,
            rocket_smoke_bottom2_animation = {
                filename = '__base__/graphics/entity/rocket-silo/12-rocket-smoke.png',
                line_length = 8,
                priority = 'medium',
                frame_count = 24,
                width = 41,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-12-rocket-smoke.png',
                    line_length = 8,
                    priority = 'medium',
                    frame_count = 24,
                    width = 80,
                    tint = {a = 0.7, r = 0.8, g = 0.8, b = 1},
                    animation_speed = 0.5,
                    scale = 0.975,
                    height = 286,
                    shift = {1.90625, 4.75}
                },
                animation_speed = 0.5,
                scale = 1.95,
                height = 145,
                tint = {a = 0.7, r = 0.8, g = 0.8, b = 1},
                shift = {1.875, 4.78125}
            },
            glow_light = {intensity = 1, color = {r = 1, g = 1, b = 1}, size = 30, shift = {0, 1.5}},
            shadow_fade_out_end_ratio = 0.75,
            rocket_flame_right_rotation = 0.952,
            rocket_air_object_slice_offset_from_center = -5.5,
            rising_speed = 0.0023809523809524,
            rocket_rise_offset = {0, -3.5},
            shadow_slave_entity = 'rocket-silo-rocket-shadow',
            rocket_visible_distance_from_center = 2.75,
            collision_mask = {'not-colliding-with-itself'},
            engine_starting_speed = 0.003030303030303,
            rocket_sprite = {
                filename = '__base__/graphics/entity/rocket-silo/02-rocket.png',
                height = 300,
                width = 154,
                shift = {-0.125, 2.625},
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-02-rocket.png',
                    scale = 0.5,
                    height = 596,
                    width = 310,
                    shift = {-0.15625, 2.65625}
                }
            },
            flying_speed = 8.3333333333333e-06,
            rocket_glare_overlay_sprite = {
                filename = '__base__/graphics/entity/rocket-silo/03-rocket-over-glare.png',
                blend_mode = 'additive',
                height = 481,
                width = 481,
                shift = {-0.0625, 6.9375},
                flags = {'linear-magnification', 'linear-minification'}
            },
            rocket_smoke_top2_animation = {
                filename = '__base__/graphics/entity/rocket-silo/12-rocket-smoke.png',
                line_length = 8,
                priority = 'medium',
                frame_count = 24,
                width = 41,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-12-rocket-smoke.png',
                    line_length = 8,
                    priority = 'medium',
                    frame_count = 24,
                    width = 80,
                    tint = {a = 0.8, r = 0.8, g = 0.8, b = 1},
                    animation_speed = 0.5,
                    scale = 0.975,
                    height = 286,
                    shift = {0.5, 6.5625}
                },
                animation_speed = 0.5,
                scale = 1.95,
                height = 145,
                tint = {a = 0.8, r = 0.8, g = 0.8, b = 1},
                shift = {0.46875, 6.59375}
            },
            rocket_launch_offset = {0, -256},
            rocket_render_layer_switch_distance = 7.5,
            rocket_smoke_top1_animation = {
                filename = '__base__/graphics/entity/rocket-silo/12-rocket-smoke.png',
                line_length = 8,
                priority = 'medium',
                frame_count = 24,
                width = 41,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-12-rocket-smoke.png',
                    line_length = 8,
                    priority = 'medium',
                    frame_count = 24,
                    width = 80,
                    tint = {a = 0.8, r = 0.8, g = 0.8, b = 1},
                    animation_speed = 0.5,
                    scale = 0.975,
                    height = 286,
                    shift = {-2.09375, 5.53125}
                },
                animation_speed = 0.5,
                scale = 1.95,
                height = 145,
                tint = {a = 0.8, r = 0.8, g = 0.8, b = 1},
                shift = {-2.125, 5.5625}
            },
            flags = {'not-on-map'},
            rocket_smoke_bottom1_animation = {
                filename = '__base__/graphics/entity/rocket-silo/12-rocket-smoke.png',
                line_length = 8,
                priority = 'medium',
                frame_count = 24,
                width = 41,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-12-rocket-smoke.png',
                    line_length = 8,
                    priority = 'medium',
                    frame_count = 24,
                    width = 80,
                    tint = {a = 0.7, r = 0.8, g = 0.8, b = 1},
                    animation_speed = 0.5,
                    scale = 0.975,
                    height = 286,
                    shift = {-2.1875, 4.6875}
                },
                animation_speed = 0.5,
                scale = 1.95,
                height = 145,
                tint = {a = 0.7, r = 0.8, g = 0.8, b = 1},
                shift = {-2.21875, 4.71875}
            },
            inventory_size = 1,
            rocket_smoke_top3_animation = {
                filename = '__base__/graphics/entity/rocket-silo/12-rocket-smoke.png',
                line_length = 8,
                priority = 'medium',
                frame_count = 24,
                width = 41,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-12-rocket-smoke.png',
                    line_length = 8,
                    priority = 'medium',
                    frame_count = 24,
                    width = 80,
                    tint = {a = 0.8, r = 0.8, g = 0.8, b = 1},
                    animation_speed = 0.5,
                    scale = 0.975,
                    height = 286,
                    shift = {1.46875, 6.15625}
                },
                animation_speed = 0.5,
                scale = 1.95,
                height = 145,
                tint = {a = 0.8, r = 0.8, g = 0.8, b = 1},
                shift = {1.4375, 6.1875}
            },
            selection_box = {{0, 0}, {0, 0}},
            name = 'rocket-silo-rocket',
            rocket_shadow_sprite = {
                filename = '__base__/graphics/entity/rocket-silo/09-rocket-shadow.png',
                draw_as_shadow = true,
                priority = 'medium',
                height = 110,
                width = 336,
                shift = {0, 0},
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-09-rocket-shadow.png',
                    draw_as_shadow = true,
                    priority = 'medium',
                    scale = 0.5,
                    height = 216,
                    width = 672,
                    shift = {0, 0.03125}
                }
            },
            rocket_flame_animation = {
                filename = '__base__/graphics/entity/rocket-silo/10-jet-flame.png',
                line_length = 8,
                blend_mode = 'additive',
                frame_count = 8,
                width = 87,
                hr_version = {
                    filename = '__base__/graphics/entity/rocket-silo/hr-10-jet-flame.png',
                    line_length = 8,
                    blend_mode = 'additive',
                    frame_count = 8,
                    width = 172,
                    animation_speed = 0.5,
                    scale = 0.565,
                    height = 256,
                    shift = {-0.0625, 8.1875},
                    priority = 'medium'
                },
                animation_speed = 0.5,
                scale = 1.13,
                height = 128,
                shift = {-0.046875, 8.1875},
                priority = 'medium'
            }
        }
    };
    return _;
end
