do
    local _ = {
        ['poison-capsule-particle-smoke'] = {
            color = {g = 0.875, r = 0.239, a = 0.69, b = 0.992},
            name = 'poison-capsule-particle-smoke',
            type = 'trivial-smoke',
            animation = {
                frame_count = 16,
                height = 50,
                scale = 0.2,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                width = 50,
                priority = 'high',
                animation_speed = 0.26666666666667
            },
            render_layer = 'higher-object-above',
            fade_away_duration = 60,
            duration = 60
        },
        ['fire-smoke-without-glow'] = {
            color = {g = 0.25, r = 0.25, a = 0.25, b = 0.25},
            name = 'fire-smoke-without-glow',
            cyclic = true,
            start_scale = 0.5,
            duration = 300,
            spread_duration = 600,
            type = 'trivial-smoke',
            fade_away_duration = 90,
            animation = {
                height = 210,
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke.png',
                width = 253,
                shift = {-0.265625, -0.09375},
                frame_count = 60,
                axially_symmetrical = false,
                priority = 'high',
                direction_count = 1,
                line_length = 8,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 60,
            affected_by_wind = true,
            end_scale = 1
        },
        ['smoke-building'] = {
            fade_away_duration = 20,
            name = 'smoke-building',
            render_layer = 'building-smoke',
            movement_slow_down_factor = 0.96,
            duration = 45,
            show_when_smoke_off = true,
            animation = {
                frame_count = 16,
                height = 50,
                scale = 0.5,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                width = 50,
                priority = 'high',
                animation_speed = 0.5
            },
            affected_by_wind = false,
            type = 'trivial-smoke'
        },
        ['smoke-explosion-lower-particle-small'] = {
            fade_away_duration = 60,
            name = 'smoke-explosion-lower-particle-small',
            render_layer = 'smoke',
            movement_slow_down_factor = 0.96,
            duration = 150,
            show_when_smoke_off = true,
            type = 'trivial-smoke',
            animation = {
                width = 50,
                frame_count = 16,
                height = 50,
                scale = 0.25,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                tint = {g = 0.1, r = 0.1, a = 0.7, b = 0.1},
                priority = 'high',
                animation_speed = 0.5
            },
            start_scale = 0.3,
            affected_by_wind = false,
            end_scale = 0.1
        },
        ['smoke-explosion-particle-tiny'] = {
            fade_away_duration = 60,
            name = 'smoke-explosion-particle-tiny',
            render_layer = 'object',
            movement_slow_down_factor = 0.96,
            duration = 150,
            show_when_smoke_off = true,
            type = 'trivial-smoke',
            animation = {
                width = 50,
                frame_count = 16,
                height = 50,
                scale = 0.2,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                tint = {g = 0.1, r = 0.1, a = 0.5, b = 0.1},
                priority = 'high',
                animation_speed = 0.5
            },
            start_scale = 0.1,
            affected_by_wind = false,
            end_scale = 0.1
        },
        ['car-smoke'] = {
            color = {g = 0.5, r = 0.5, a = 0.5, b = 0.5},
            name = 'car-smoke',
            cyclic = true,
            start_scale = 0.1,
            duration = 12,
            spread_duration = 12,
            type = 'trivial-smoke',
            fade_away_duration = 12,
            animation = {
                height = 120,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                width = 152,
                frame_count = 60,
                priority = 'high',
                shift = {-0.53125, -0.4375},
                line_length = 5,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 0,
            affected_by_wind = true,
            end_scale = 0.5
        },
        ['smoke-explosion-particle-stone-small'] = {
            fade_away_duration = 60,
            name = 'smoke-explosion-particle-stone-small',
            render_layer = 'smoke',
            movement_slow_down_factor = 0.96,
            duration = 150,
            show_when_smoke_off = true,
            type = 'trivial-smoke',
            animation = {
                width = 50,
                frame_count = 16,
                height = 50,
                scale = 0.25,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                tint = {g = 0.502, r = 0.604, a = 0.7, b = 0.4},
                priority = 'high',
                animation_speed = 0.5
            },
            start_scale = 0.3,
            affected_by_wind = false,
            end_scale = 0.1
        },
        ['fire-smoke-on-adding-fuel'] = {
            cyclic = true,
            name = 'fire-smoke-on-adding-fuel',
            spread_duration = 600,
            duration = 300,
            start_scale = 0.5,
            type = 'trivial-smoke',
            fade_away_duration = 60,
            animation = {
                height = 210,
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke.png',
                width = 253,
                shift = {-0.265625, -0.09375},
                frame_count = 60,
                axially_symmetrical = false,
                priority = 'high',
                direction_count = 1,
                line_length = 8,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 60,
            affected_by_wind = true,
            end_scale = 0.7
        },
        ['smoke-explosion-particle-small'] = {
            fade_away_duration = 60,
            name = 'smoke-explosion-particle-small',
            render_layer = 'smoke',
            movement_slow_down_factor = 0.96,
            duration = 150,
            show_when_smoke_off = true,
            type = 'trivial-smoke',
            animation = {
                width = 50,
                frame_count = 16,
                height = 50,
                scale = 0.25,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                tint = {g = 0.1, r = 0.1, a = 0.7, b = 0.1},
                priority = 'high',
                animation_speed = 0.5
            },
            start_scale = 0.3,
            affected_by_wind = false,
            end_scale = 0.1
        },
        smoke = {
            color = {g = 0.4, r = 0.4, a = 0.4, b = 0.4},
            name = 'smoke',
            cyclic = true,
            start_scale = 0.2,
            duration = 600,
            spread_duration = 600,
            type = 'trivial-smoke',
            fade_away_duration = 600,
            animation = {
                height = 120,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                width = 152,
                frame_count = 60,
                priority = 'high',
                shift = {-0.53125, -0.4375},
                line_length = 5,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 0,
            affected_by_wind = true,
            end_scale = 1
        },
        ['smoke-fast'] = {
            duration = 60,
            name = 'smoke-fast',
            type = 'trivial-smoke',
            animation = {
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                width = 50,
                priority = 'high',
                animation_speed = 0.26666666666667
            },
            fade_away_duration = 60
        },
        ['soft-fire-smoke'] = {
            color = {g = 0.03, r = 0.03, a = 0.1, b = 0.03},
            name = 'soft-fire-smoke',
            cyclic = true,
            start_scale = 0.5,
            duration = 300,
            spread_duration = 600,
            type = 'trivial-smoke',
            fade_away_duration = 60,
            animation = {
                height = 120,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                width = 152,
                shift = {-0.53125, -0.4375},
                frame_count = 60,
                axially_symmetrical = false,
                priority = 'high',
                direction_count = 1,
                line_length = 5,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 0,
            affected_by_wind = true,
            end_scale = 1.2
        },
        ['nuclear-smoke'] = {
            color = {g = 0.478, r = 0.627, a = 0.5, b = 0.345},
            name = 'nuclear-smoke',
            render_layer = 'higher-object-under',
            cyclic = true,
            start_scale = 2,
            duration = 30,
            spread_duration = 100,
            type = 'trivial-smoke',
            fade_away_duration = 20,
            animation = {
                frame_count = 16,
                height = 50,
                scale = 2.5,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                width = 50,
                priority = 'high',
                animation_speed = 0.16666666666667
            },
            fade_in_duration = 10,
            affected_by_wind = true,
            end_scale = 0.2
        },
        ['fire-smoke'] = {
            color = {g = 0.4, r = 0.4, a = 0.25, b = 0.4},
            glow_fade_away_duration = 70,
            glow_animation = {
                blend_mode = 'additive',
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke-glow.png',
                width = 253,
                shift = {-0.265625, 0.8125},
                priority = 'high',
                frame_count = 60,
                axially_symmetrical = false,
                line_length = 8,
                direction_count = 1,
                height = 152,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            cyclic = true,
            start_scale = 0.5,
            spread_duration = 600,
            duration = 300,
            name = 'fire-smoke',
            type = 'trivial-smoke',
            fade_away_duration = 90,
            animation = {
                height = 210,
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke.png',
                width = 253,
                shift = {-0.265625, -0.09375},
                frame_count = 60,
                axially_symmetrical = false,
                priority = 'high',
                direction_count = 1,
                line_length = 8,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 60,
            affected_by_wind = true,
            end_scale = 1
        },
        ['artillery-smoke'] = {
            fade_away_duration = 20,
            name = 'artillery-smoke',
            render_layer = 'building-smoke',
            movement_slow_down_factor = 0.96,
            duration = 105,
            show_when_smoke_off = true,
            animation = {
                frame_count = 16,
                height = 50,
                scale = 0.5,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                width = 50,
                priority = 'high',
                animation_speed = 0.16666666666667
            },
            affected_by_wind = false,
            type = 'trivial-smoke'
        },
        ['turbine-smoke'] = {
            color = {g = 0.5, r = 0.5, a = 0.3, b = 0.5},
            name = 'turbine-smoke',
            cyclic = true,
            start_scale = 0.8,
            duration = 600,
            spread_duration = 600,
            type = 'trivial-smoke',
            fade_away_duration = 570,
            animation = {
                height = 120,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                width = 152,
                frame_count = 60,
                priority = 'high',
                shift = {-0.53125, -0.4375},
                line_length = 5,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 30,
            affected_by_wind = true,
            end_scale = 1
        },
        ['light-smoke'] = {
            color = {g = 0.5, r = 0.5, a = 0.3, b = 0.5},
            name = 'light-smoke',
            cyclic = true,
            start_scale = 0.2,
            duration = 600,
            spread_duration = 600,
            type = 'trivial-smoke',
            fade_away_duration = 600,
            animation = {
                height = 120,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                width = 152,
                frame_count = 60,
                priority = 'high',
                shift = {-0.53125, -0.4375},
                line_length = 5,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 0,
            affected_by_wind = true,
            end_scale = 1
        },
        ['train-smoke'] = {
            color = {g = 0.3, r = 0.3, a = 0.3, b = 0.3},
            name = 'train-smoke',
            cyclic = true,
            start_scale = 0.4,
            duration = 150,
            spread_duration = 100,
            type = 'trivial-smoke',
            fade_away_duration = 100,
            animation = {
                height = 120,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                width = 152,
                frame_count = 60,
                priority = 'high',
                shift = {-0.53125, -0.4375},
                line_length = 5,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 0,
            affected_by_wind = true,
            end_scale = 1.5
        },
        ['smoke-explosion-particle'] = {
            fade_away_duration = 60,
            name = 'smoke-explosion-particle',
            render_layer = 'smoke',
            movement_slow_down_factor = 0.96,
            duration = 150,
            show_when_smoke_off = true,
            animation = {
                width = 50,
                frame_count = 16,
                height = 50,
                scale = 0.5,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                tint = {g = 0.1, r = 0.1, a = 0.7, b = 0.1},
                priority = 'high',
                animation_speed = 0.5
            },
            affected_by_wind = false,
            type = 'trivial-smoke'
        },
        ['tank-smoke'] = {
            color = {g = 0.5, r = 0.5, a = 0.5, b = 0.5},
            name = 'tank-smoke',
            cyclic = true,
            start_scale = 0.3,
            duration = 100,
            spread_duration = 100,
            type = 'trivial-smoke',
            fade_away_duration = 100,
            animation = {
                height = 120,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                width = 152,
                frame_count = 60,
                priority = 'high',
                shift = {-0.53125, -0.4375},
                line_length = 5,
                flags = {'smoke'},
                animation_speed = 0.25
            },
            fade_in_duration = 0,
            affected_by_wind = true,
            end_scale = 1
        },
        ['poison-capsule-smoke'] = {
            color = {g = 0.875, r = 0.239, a = 0.69, b = 0.992},
            name = 'poison-capsule-smoke',
            type = 'trivial-smoke',
            animation = {
                frame_count = 16,
                height = 50,
                scale = 0.5,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                width = 50,
                priority = 'high',
                animation_speed = 0.26666666666667
            },
            render_layer = 'higher-object-above',
            fade_away_duration = 60,
            duration = 60
        },
        ['smoke-train-stop'] = {
            fade_away_duration = 30,
            name = 'smoke-train-stop',
            render_layer = 'lower-object',
            movement_slow_down_factor = 0.95,
            duration = 40,
            show_when_smoke_off = true,
            animation = {
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png',
                width = 50,
                priority = 'high',
                animation_speed = 0.26666666666667
            },
            affected_by_wind = false,
            type = 'trivial-smoke'
        }
    };
    return _;
end
