do
    local _ = {
        ['smoke-explosion-lower-particle-small'] = {
            movement_slow_down_factor = 0.96,
            affected_by_wind = false,
            duration = 150,
            start_scale = 0.3,
            animation = {
                width = 50,
                animation_speed = 0.5,
                scale = 0.25,
                tint = {a = 0.7, b = 0.1, g = 0.1, r = 0.1},
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            render_layer = 'smoke',
            end_scale = 0.1,
            name = 'smoke-explosion-lower-particle-small',
            fade_away_duration = 60
        },
        ['fire-smoke-on-adding-fuel'] = {
            spread_duration = 600,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.5,
            animation = {
                direction_count = 1,
                animation_speed = 0.25,
                width = 253,
                flags = {'smoke'},
                axially_symmetrical = false,
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke.png',
                priority = 'high',
                line_length = 8,
                frame_count = 60,
                shift = {-0.265625, -0.09375},
                height = 210
            },
            type = 'trivial-smoke',
            fade_away_duration = 60,
            fade_in_duration = 60,
            end_scale = 0.7,
            name = 'fire-smoke-on-adding-fuel',
            duration = 300
        },
        ['fire-smoke-without-glow'] = {
            spread_duration = 600,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.5,
            animation = {
                direction_count = 1,
                animation_speed = 0.25,
                width = 253,
                flags = {'smoke'},
                axially_symmetrical = false,
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke.png',
                priority = 'high',
                line_length = 8,
                frame_count = 60,
                shift = {-0.265625, -0.09375},
                height = 210
            },
            color = {a = 0.25, b = 0.25, g = 0.25, r = 0.25},
            type = 'trivial-smoke',
            fade_away_duration = 90,
            fade_in_duration = 60,
            end_scale = 1,
            name = 'fire-smoke-without-glow',
            duration = 300
        },
        ['smoke-building'] = {
            movement_slow_down_factor = 0.96,
            affected_by_wind = false,
            duration = 45,
            animation = {
                animation_speed = 0.5,
                scale = 0.5,
                width = 50,
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            fade_away_duration = 20,
            name = 'smoke-building',
            render_layer = 'building-smoke'
        },
        ['nuclear-smoke'] = {
            spread_duration = 100,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 2,
            animation = {
                animation_speed = 0.16666666666667,
                scale = 2.5,
                width = 50,
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            color = {a = 0.5, b = 0.345, g = 0.478, r = 0.627},
            type = 'trivial-smoke',
            render_layer = 'higher-object-under',
            fade_away_duration = 20,
            fade_in_duration = 10,
            end_scale = 0.2,
            name = 'nuclear-smoke',
            duration = 30
        },
        ['tank-smoke'] = {
            spread_duration = 100,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.3,
            animation = {
                animation_speed = 0.25,
                width = 152,
                flags = {'smoke'},
                priority = 'high',
                filename = '__base__/graphics/entity/smoke/smoke.png',
                line_length = 5,
                frame_count = 60,
                shift = {-0.53125, -0.4375},
                height = 120
            },
            color = {a = 0.5, b = 0.5, g = 0.5, r = 0.5},
            type = 'trivial-smoke',
            fade_away_duration = 100,
            fade_in_duration = 0,
            end_scale = 1,
            name = 'tank-smoke',
            duration = 100
        },
        ['smoke-explosion-particle'] = {
            movement_slow_down_factor = 0.96,
            affected_by_wind = false,
            duration = 150,
            animation = {
                width = 50,
                animation_speed = 0.5,
                scale = 0.5,
                tint = {a = 0.7, b = 0.1, g = 0.1, r = 0.1},
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            fade_away_duration = 60,
            name = 'smoke-explosion-particle',
            render_layer = 'smoke'
        },
        ['artillery-smoke'] = {
            movement_slow_down_factor = 0.96,
            affected_by_wind = false,
            duration = 105,
            animation = {
                animation_speed = 0.16666666666667,
                scale = 0.5,
                width = 50,
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            fade_away_duration = 20,
            name = 'artillery-smoke',
            render_layer = 'building-smoke'
        },
        ['smoke-fast'] = {
            type = 'trivial-smoke',
            fade_away_duration = 60,
            duration = 60,
            name = 'smoke-fast',
            animation = {
                animation_speed = 0.26666666666667,
                width = 50,
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            }
        },
        ['turbine-smoke'] = {
            spread_duration = 600,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.8,
            animation = {
                animation_speed = 0.25,
                width = 152,
                flags = {'smoke'},
                priority = 'high',
                filename = '__base__/graphics/entity/smoke/smoke.png',
                line_length = 5,
                frame_count = 60,
                shift = {-0.53125, -0.4375},
                height = 120
            },
            color = {a = 0.3, b = 0.5, g = 0.5, r = 0.5},
            type = 'trivial-smoke',
            fade_away_duration = 570,
            fade_in_duration = 30,
            end_scale = 1,
            name = 'turbine-smoke',
            duration = 600
        },
        ['train-smoke'] = {
            spread_duration = 100,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.4,
            animation = {
                animation_speed = 0.25,
                width = 152,
                flags = {'smoke'},
                priority = 'high',
                filename = '__base__/graphics/entity/smoke/smoke.png',
                line_length = 5,
                frame_count = 60,
                shift = {-0.53125, -0.4375},
                height = 120
            },
            color = {a = 0.3, b = 0.3, g = 0.3, r = 0.3},
            type = 'trivial-smoke',
            fade_away_duration = 100,
            fade_in_duration = 0,
            end_scale = 1.5,
            name = 'train-smoke',
            duration = 150
        },
        ['light-smoke'] = {
            spread_duration = 600,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.2,
            animation = {
                animation_speed = 0.25,
                width = 152,
                flags = {'smoke'},
                priority = 'high',
                filename = '__base__/graphics/entity/smoke/smoke.png',
                line_length = 5,
                frame_count = 60,
                shift = {-0.53125, -0.4375},
                height = 120
            },
            color = {a = 0.3, b = 0.5, g = 0.5, r = 0.5},
            type = 'trivial-smoke',
            fade_away_duration = 600,
            fade_in_duration = 0,
            end_scale = 1,
            name = 'light-smoke',
            duration = 600
        },
        ['soft-fire-smoke'] = {
            spread_duration = 600,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.5,
            animation = {
                direction_count = 1,
                animation_speed = 0.25,
                width = 152,
                flags = {'smoke'},
                axially_symmetrical = false,
                filename = '__base__/graphics/entity/smoke/smoke.png',
                priority = 'high',
                line_length = 5,
                frame_count = 60,
                shift = {-0.53125, -0.4375},
                height = 120
            },
            color = {a = 0.1, b = 0.03, g = 0.03, r = 0.03},
            type = 'trivial-smoke',
            fade_away_duration = 60,
            fade_in_duration = 0,
            end_scale = 1.2,
            name = 'soft-fire-smoke',
            duration = 300
        },
        ['car-smoke'] = {
            spread_duration = 12,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.1,
            animation = {
                animation_speed = 0.25,
                width = 152,
                flags = {'smoke'},
                priority = 'high',
                filename = '__base__/graphics/entity/smoke/smoke.png',
                line_length = 5,
                frame_count = 60,
                shift = {-0.53125, -0.4375},
                height = 120
            },
            color = {a = 0.5, b = 0.5, g = 0.5, r = 0.5},
            type = 'trivial-smoke',
            fade_away_duration = 12,
            fade_in_duration = 0,
            end_scale = 0.5,
            name = 'car-smoke',
            duration = 12
        },
        ['smoke-train-stop'] = {
            movement_slow_down_factor = 0.95,
            affected_by_wind = false,
            duration = 40,
            animation = {
                animation_speed = 0.26666666666667,
                width = 50,
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            fade_away_duration = 30,
            name = 'smoke-train-stop',
            render_layer = 'lower-object'
        },
        smoke = {
            spread_duration = 600,
            affected_by_wind = true,
            cyclic = true,
            start_scale = 0.2,
            animation = {
                animation_speed = 0.25,
                width = 152,
                flags = {'smoke'},
                priority = 'high',
                filename = '__base__/graphics/entity/smoke/smoke.png',
                line_length = 5,
                frame_count = 60,
                shift = {-0.53125, -0.4375},
                height = 120
            },
            color = {a = 0.4, b = 0.4, g = 0.4, r = 0.4},
            type = 'trivial-smoke',
            fade_away_duration = 600,
            fade_in_duration = 0,
            end_scale = 1,
            name = 'smoke',
            duration = 600
        },
        ['smoke-explosion-particle-tiny'] = {
            movement_slow_down_factor = 0.96,
            affected_by_wind = false,
            duration = 150,
            start_scale = 0.1,
            animation = {
                width = 50,
                animation_speed = 0.5,
                scale = 0.2,
                tint = {a = 0.5, b = 0.1, g = 0.1, r = 0.1},
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            render_layer = 'object',
            end_scale = 0.1,
            name = 'smoke-explosion-particle-tiny',
            fade_away_duration = 60
        },
        ['poison-capsule-particle-smoke'] = {
            color = {a = 0.69, b = 0.992, g = 0.875, r = 0.239},
            type = 'trivial-smoke',
            render_layer = 'higher-object-above',
            fade_away_duration = 60,
            duration = 60,
            name = 'poison-capsule-particle-smoke',
            animation = {
                animation_speed = 0.26666666666667,
                scale = 0.2,
                width = 50,
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            }
        },
        ['smoke-explosion-particle-small'] = {
            movement_slow_down_factor = 0.96,
            affected_by_wind = false,
            duration = 150,
            start_scale = 0.3,
            animation = {
                width = 50,
                animation_speed = 0.5,
                scale = 0.25,
                tint = {a = 0.7, b = 0.1, g = 0.1, r = 0.1},
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            render_layer = 'smoke',
            end_scale = 0.1,
            name = 'smoke-explosion-particle-small',
            fade_away_duration = 60
        },
        ['poison-capsule-smoke'] = {
            color = {a = 0.69, b = 0.992, g = 0.875, r = 0.239},
            type = 'trivial-smoke',
            render_layer = 'higher-object-above',
            fade_away_duration = 60,
            duration = 60,
            name = 'poison-capsule-smoke',
            animation = {
                animation_speed = 0.26666666666667,
                scale = 0.5,
                width = 50,
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            }
        },
        ['fire-smoke'] = {
            spread_duration = 600,
            affected_by_wind = true,
            type = 'trivial-smoke',
            cyclic = true,
            start_scale = 0.5,
            animation = {
                direction_count = 1,
                animation_speed = 0.25,
                width = 253,
                flags = {'smoke'},
                axially_symmetrical = false,
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke.png',
                priority = 'high',
                line_length = 8,
                frame_count = 60,
                shift = {-0.265625, -0.09375},
                height = 210
            },
            color = {a = 0.25, b = 0.4, g = 0.4, r = 0.4},
            fade_away_duration = 90,
            glow_fade_away_duration = 70,
            glow_animation = {
                direction_count = 1,
                animation_speed = 0.25,
                width = 253,
                flags = {'smoke'},
                axially_symmetrical = false,
                blend_mode = 'additive',
                filename = '__base__/graphics/entity/fire-smoke/fire-smoke-glow.png',
                priority = 'high',
                line_length = 8,
                frame_count = 60,
                shift = {-0.265625, 0.8125},
                height = 152
            },
            fade_in_duration = 60,
            end_scale = 1,
            name = 'fire-smoke',
            duration = 300
        },
        ['smoke-explosion-particle-stone-small'] = {
            movement_slow_down_factor = 0.96,
            affected_by_wind = false,
            duration = 150,
            start_scale = 0.3,
            animation = {
                width = 50,
                animation_speed = 0.5,
                scale = 0.25,
                tint = {a = 0.7, b = 0.4, g = 0.502, r = 0.604},
                priority = 'high',
                frame_count = 16,
                height = 50,
                filename = '__base__/graphics/entity/smoke-fast/smoke-fast.png'
            },
            type = 'trivial-smoke',
            show_when_smoke_off = true,
            render_layer = 'smoke',
            end_scale = 0.1,
            name = 'smoke-explosion-particle-stone-small',
            fade_away_duration = 60
        }
    };
    return _;
end
