-- Empty file to trick Factorio into thinking this mod changes the game.
-- Without this file STDLIB will not be synced in MP as Factorio thinks
-- it is a non game changing mod (I.E translation only)
