-- -- Put a custom path searcher at the top of the list, to replace __stdlib__ in paths.
-- package.cpath = ''
-- print(package.path)
-- print(package.searchpath)
-- local function searcher(path)
--     if path:find('^%_%_stdlib%_%_') then
--         local newpath = path:gsub('^%_%_stdlib%_%_/', '')
--         return require(newpath)
--     end
-- end
-- table.insert(package.searchers, 1, searcher)
